---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tdarr
  namespace: media
spec:
  maxHistory: 3
  interval: 5m
  suspend: false
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    defaultPodOptions:
      securityContext:
        capabilities:
          add:
            - CHOWN
        fsGroupChangePolicy: "OnRootMismatch"
        # Required for passthrough of /dev/dri devices from NFD
        # https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-focal.html
        supplementalGroups:
          - 44
          - 109
    controllers:
      main:
        type: deployment
        containers:
          main:
            image:
              repository: ghcr.io/haveagitgat/tdarr_acc
              tag: 2.23.01
              pullPolicy: IfNotPresent
            env:
              webUIPort: &web-port 8265
              serverIP: 0.0.0.0
              serverPort: &server-port 8266
              TZ: ${TZ}
              ffmpegPath: "/usr/local/bin/ffmpeg"
              PGID: 65537
            resources:
              requests:
                cpu: 10m
                memory: 250Mi

    persistence:
      server:
        enabled: true
        existingClaim: tdarr-serverdata-v1
        globalMounts:
          - path: /app/server
      config:
        enabled: true
        existingClaim: tdarr-config-v1
        globalMounts:
          - path: /app/configs
      media:
        enabled: true
        type: nfs
        server: "${NFS_SERVER}"
        path: /volume1/Media
        mountPath: /media
        readOnly: false
      cache:
        enabled: true
        type: nfs
        server: "${NFS_SERVER}"
        path: ${NFS_MEDIA}/cache
        mountPath: /cache

    service:
      main:
        ports:
          http:
            port: *web-port
          server:
            enabled: true
            protocol: TCP
            port: *server-port

    ingress:
      main:
        enabled: true
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/instance: "bloop-quarky"
          hajimari.io/icon: material-symbols:switch-video-outline
          hajimari.io/group: media
        hosts:
          - host: &host tdarr.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: nodetype
                  operator: In
                  values:
                    - worker
