---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age17mejdfq9mpp3uhqenmtrhuxs598atx33telpakcwcp59wzrg3q6qcl34w0"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age17mejdfq9mpp3uhqenmtrhuxs598atx33telpakcwcp59wzrg3q6qcl34w0"
