---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mylar
  namespace: organizers
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mylar-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MYLAR__API_KEY: "{{ .MYLAR__API_KEY }}"
  dataFrom:
    - extract:
        key: MYLAR
