apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:ad4k3xsaA/80njMNGC9OSM7BEARiDJD5CUv8lqGAmns6WCtp,iv:ozYHqIYnGsAI5x9u+J3JY7+xzPQm+8tmlOJvWnol3NU=,tag:R4PXl+Xk51ND92lif3/UYQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:4wtq+qng8meU+4rR46zfyZ0/62RnL9xxDBhHb+kv+AJSkLR/wxsJGayO2iHtExL0NWRBww8Op6qdN235wMrMZWXV001L8Syq4I3kJTelNgaNR3tehp7ijppvH4qymrxO5nPJxETRisDUZ6d0wrIPfjxwY7XnjmSK/neusIzM5KSAsap7E2T1reqaFvPeTfa4JQV9PTKl3PzpjXz1tX1nKrIQTOjiIiKia6L+8yXhCQ==,iv:z2i0BE1LJgz+4+0bpylCYF5VPCQHXkxPhZcDk4p5BDU=,tag:LX4WLdt6EfvVzR5m9XOY/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13zy8tnl795dry8956zwaa9czept9erhcz6cvrup8md4p0s9465jq83mnp9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dEF2bXlHYkllZnlEQk9h
            dWJZejY5a0dwTUZ5bzdHajh5ajF1L3ZqYTIwCnJtdDNQMHVIQ1RTODc5MGJFMk5W
            ck10RXJNN09Nb09LZnpkZWx3Q3phQVEKLS0tIHA2ZUk0a1ZlMjY3MWdMUDV4NG9O
            a0tjcFRaK29DL055dUdiUUR5SWZOWDAKR3rVk4q3AxPBokqpBWFkd+zmFX6rLfFW
            iEr7lf7ShGva6jEq8CTgxU0gEMiKEgtBhUxtc4l02g3kxni5BdTTlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-16T21:00:53Z"
    mac: ENC[AES256_GCM,data:hQ/cie/ZA7UW1yS0j5lexeYeydZ27sbksT5ycgHtCoUvZUBwasdR0ISqHi/RTfciMnJ2FJs8WMjm8qFf4hOkuQ/zv7D4EiOkp18cWCUm1R6aWneZED6gHGELoYegi7YlQpjvWI0Dzuy21QDJt0HyYSLGxYtcPUXwLJfhiKLH/vI=,iv:YErOuoFSCiOlEUnKj5EyUvIaBXgCNCkgRG25AVwtIP0=,tag:uMu40xrSVrgOg8w14FsnaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
