apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:E8i8QPbfo+YsbThBgCofh9v5cq0Me1xu39W3gkQ7ek3j5G1g,iv:d+Ccwt9OzSj6b90XsgMktUZn/ZqV8b8zxZYJyiwqCws=,tag:uXUMfQKlm5s0AeHBghnSuA==,type:str]
    credentials.json: ENC[AES256_GCM,data:5HqFYnfbdDJVI8drq8RFV3C+gPH9LgJmi6Sy5j678cukJMwbxb7IvcZAvng+MKaDLGGL1PsUJfDOInobENQZ8/2Vadrol8oTXyBAZMwjNNSe1gZDoVZcCIger1XSEUC6S605Hh6bXlNBvfLaGOjQaiMmr0XV542z5VrLuqV6CI5z8hlNfLamreY38nvOk8V7z7yfRdrFreMM+KmHzmW5eeFndXEHQaqiex0tOFZV5Q==,iv:2NX69mgpKjf0MarLzQ95oF371B8Yz4ryx1sKANF5DHM=,tag:rMLBFPtNOIUBXuFvt3mQWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17mejdfq9mpp3uhqenmtrhuxs598atx33telpakcwcp59wzrg3q6qcl34w0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvblNZRzdYTTRaZmJjd1NK
            ei9CVzl6alE5SlVSbW9qSmNzVWpBZUpBOGdZCmJzZGc5R21RWUJzSjJxWTh4aG0r
            cXpvRHpvaVlmY0hxdmgrRkhqclBsNG8KLS0tIHMrazRpNEtLYm8wNGtUUC9Ga05W
            YzJaczBKSGZTR0RSbE1zRFY1bDBpeU0KddJdCDEYURPpWkBwMen/K/tme4uKsewC
            6PDk/Yrqi3ph6JQo8NQSUmdz8EntOfRnsVkODNsnE8FriUM2l/r7kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-27T02:54:57Z"
    mac: ENC[AES256_GCM,data:S4B7lHPi76kQld99uy2E5U9/d4tKYX6TsApJISjzz733N/ieGhdkLhXx8xel/Xmv/SHMjBgpZRifyXpPnkaFvjuH7JNvTUgK5zy+/rrkJMj6Z3zMOifGvxoNMALriG1VzJ6I2P9W7bZRTOanLWObRoQ+vTBmZkcMbZs/bD+RYCw=,iv:b3Aj5BJ5quZ8MhKZdYBTyDjJtewfNrWxX5iOpq/zeaU=,tag:YRlYnnV47crU4nmab+c/Xw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
