apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:JPl02gFdXUZEb7S4C8DqHQXgwWUPMmJdDd0FlXTHbAvt16NX,iv:7BWzmr7NAzj/S4qaZOj8jjoP2k+OcDwvYqjub8tASkY=,tag:gmPuODCdaHS7nWkb7JDKSw==,type:str]
    credentials.json: ENC[AES256_GCM,data:zAyqOXaV6+nFqhRL9M8WKZz/Tr3wiNDmq/Pf/RTXejxRF928CA7QVzz2VRHKqweU0LfYk2N7D5JWieKaShWfa63AVPEb9piVOH5QDOKN7l5vSJHSsTJp0trBk0M81oXWLwVCutJQHuTvf1K+DXSAl4o8dOEvaqaan9Az1GUpf3/mCMgpw4oj3y/kVU+lTdNRAybJkRr0Sfayf+Jlq8guQCSTb13NBd8VrWJIAN+ccA==,iv:gNdk5FxykSkDywFKTF6umutBFJ3sPbZrmtVSzCoFQdo=,tag:Fev1UvCcdE1Ycq7IXbwe9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13zy8tnl795dry8956zwaa9czept9erhcz6cvrup8md4p0s9465jq83mnp9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUStTTEJtTGhNOThwbm5W
            KzRkWWc4d3NVakF3c2xadUVmc0VDSndLRUdNCmFpWEdTbENQZlBIMktyeDRzc1hk
            bWJ1U1ZzT3RiME9rZmJ2V1NUTnp4WEEKLS0tIEluOGNNNUpPRUVMYTYwbjN0Q0d0
            UmxicVBzNXhWY3ZUZXJRamhSQzNQaVkKOaHvXQXD3WQTt8oodcaqdYyA2pDkGCA2
            yq3AdvFU4fAX6ho0wnZ2S1muTsPl+oyeJVOlKJPuqMlYBwjVgaUicQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-28T07:43:53Z"
    mac: ENC[AES256_GCM,data:OtJiAhheEJdNgznH5Hkkyg0wL3uiLJ5xJPNfJEa1hRUmsa91BkEoNyec70BWrea0l4WZT8130Hy2/Z+ajJYtLlmf1lCxFCsgri0SrH0FzfhAxcG63q6Pt63QO+qEmVyfaCACbzWjgXO3MInJ6+JWMBaiQNTaIzU9nCJS0xaAbuI=,iv:eAjBiw4FORMCRJzJS8LcesNVTULmAmY1bUncUJKPoHE=,tag:xVK8/za/ot5mghSeo/hXmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
