apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:KXABG83W8txdtV6PjecNGY7hyXrvsoPfZ1rcRhkXK1gJXReV,iv:c78eihoWu4RjBhHu5adBUeLdLyjbsOkG6l4nH34eq+Y=,tag:GJsI6m/1GkLsBGM3adtmyA==,type:str]
    credentials.json: ENC[AES256_GCM,data:a9zMYhIM2AeV+lDDI3HaFpGYL01ydvndE53mi0GJSu8zyX/YgllKdW5ColAX5CnGDb8Bek1XeW6mdm+2BCTcPp1WmlD2icFhFB0YtqyPyQzIYw7zXk8ugXK55NXZmdbuE1UkbNUxcEle4fPn2mKkD5m4fJytq5z8vYBsGxyABm/wQg/+fIKryNkc3nznPDkcY6gcJtRh25zsEw3tDOrA8Vm8j4ORCwamvQv1oQAQDw==,iv:0C1u86w0yB96zb2n/LMATCKB92VFXSGPWn73R0PTHI0=,tag:UxzCiewMnZf3BoXXtikZNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13zy8tnl795dry8956zwaa9czept9erhcz6cvrup8md4p0s9465jq83mnp9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQk5EbWQ2cVdzS2Y3T3Zl
            SkNVRmpST3VmSE1NYnhML0tOeHhySkdaQlFRClpsOFRYOGI3SlUzcHlWR1VIK2Q4
            cHV6VVUvaXVKOS9zdThQbmRxRUN6WkUKLS0tIEo4QklSQ1QwMVN1Zm1GeGF5SVlh
            Ky93LzRNeE5rZFBSWWgvbGQrMlRvZWcK864HHuXhOowooYwJo1WOzoja53Dhwhr2
            4wZ8GOHYjv9iEQu+JFjkX0NwVfr3ih3xloaeVJ0sylPZgSouXdktcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-28T07:50:09Z"
    mac: ENC[AES256_GCM,data:BtsYghDMFz/CySV9o/j3kDIq7l+R+en4kg+rczR0dHA9n5IuCmT/Jxvr7adgr+jc2F9rFniLdByhOvJj3yRizC16RXK6NgoIZUDqt0ZmqGTChU4yzl6XSjPv+WEkxQkR2j4oYOlMMAauSBV/mjJQts25J/H3/1XBImJeFqCAeeI=,iv:Hk3aKgA45mVpNrPTTEVYUFenDVaqsUhD6xqQN/b8GHQ=,tag:0C+BeRfVdjvPBm8+sIrvrw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
