---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-config
  namespace: media
  labels:
    app.kubernetes.io/name: &name calibre
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-block
---
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-inbox
  namespace: media
  labels:
    app.kubernetes.io/name: &name calibre
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-block
