---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app calibre
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: volsync
      namespace: system
  values:

    controllers:
      calibre:
        containers:
          app:
            image:
              repository: ghcr.io/linuxserver/calibre
              tag: 7.15.0
            env:
              TZ: ${TZ}
              PUID: '568'
              PGID: '568'
            resources:
              requests:
                cpu: 15m
                memory: 249M
              limits:
                memory: 4000M
            probes:
              startup:
                spec:
                  initialDelaySeconds: 60
                  failureThreshold: 160
    service:
      main:
        controller: *app
        ports:
          http:
            port: 8080
      webserver:
        controller: *app
        primary: false
        ports:
          webserver:
            enabled: true
            port: 8081
            protocol: TCP
            targetPort: 8081
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        loadBalancerIP: ${LB_CALIBRE}

    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host 'calibre.${EXTERNAL_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts: [*host]

    persistence:
      config:
        enabled: true
        existingClaim: calibre-config
      media:
        enabled: true
        type: nfs
        server: ${NFS_SERVER}
        path: ${NF_MEDIA}
        globalMounts:
          - path: /media
