apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:R87/LStIuLY4dC2VlhaoSFYgaLn+3XsBwiMBiNC+SEfIDPsSx/pywg==,iv:hQtwj7+JksRrIG9ZRxrC7wqPmQPEgp2gcSpM0ay2/Lo=,tag:0RuNliNQJ6tQ9OGNTAHU2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13zy8tnl795dry8956zwaa9czept9erhcz6cvrup8md4p0s9465jq83mnp9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbVZrVnQ4K2ozaFplRjVv
            RDZQT2FlRlpZVi9oa0NPd0laZ2hPOFRTQkNVCjRWckgybDV6dHlaZjVvYVJ4SWVo
            dkl1ZWloZFdVa2psOGRtSlYrRnVpbU0KLS0tIFZWSFB2SEt1S1Zhd3ZTdk1NZDZT
            UzIvdjE2b25MdGRBMmk4eXZ6bGN2dEkKS24+0CY27kt/HI8TviVAVvhtADtwbcPY
            6qIkYvXz1MAtzLnjX48AjkH2AJ4COnYaALn7R6sy1P11OGehIYShoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-16T18:50:42Z"
    mac: ENC[AES256_GCM,data:wjz0K/cPJjoK59nh0JyXesoDdw87G7l1mrxBVRFJ4lnyYuc8RxxBE2vQDcIh3SC2ICLL2JL1nCvan0XMmrUmBDHGnlSbzturpHKn190N2pzQezU8hdHLBSej6HX7SbzLetcrmQCOHoh0WtdSW/lQrc6uPr/NyJjT9m9LIYGFnIo=,iv:fp0IQo5euKpMb0xXf7kZV4iAdOnxJMSb6ubHUCDZvvA=,tag:V+yPA/66XusChYwyBJ4NQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
