apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:5OcJMBRuocT6tqI7DXG5BL1klqHPSQt/BKYo5HnQbvBlWbE0i3IH4A==,iv:LESNvOBkaQ5jOdXgEgfVkE3uEDryC8sZLWr/pAzU6a4=,tag:rRgC44hKzQxk2zF2hYh78Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17mejdfq9mpp3uhqenmtrhuxs598atx33telpakcwcp59wzrg3q6qcl34w0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnOFRqSjl6MEVsQWtRQ0tq
            Umk5c2VJWmE4aVhtTDJXSEpNeVpKcXU5NWdVClZ4akhsL2twRGtQQzYxK2prTjZw
            UThkRXgvbEpnMmZpWGNIMmQwczZNMUkKLS0tIGVLdDBQQ1ZwUUpDVlNqRVF5TjBq
            a1RlTVVOdjA4aWduclBzaUFtS2ZmZWcKvJKpLT5D4/PRg6eB/2ZoJXJVbtsGvtnr
            ZXgES0Bkl2Ewdwk+JF/JOuvl59Eqs93/J8d/mzuHcb06bOeTju+3Fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-27T03:13:41Z"
    mac: ENC[AES256_GCM,data:yJL/W92JRvJ8WL+GQGNkFm8aM1LmCzofcSiTEnCnvXd4OAN8gl3GXkwm+wH5PwCzjUeYhzd5HXYixQv6AiTl0wQfAsnWOgJBj9vwmeyAF4MAlpeP+imsV1jsCAJ7tTJ+Y5IhZ6PRazi9S6QMtOOLcmlxnN/2yt1IXrq/+7F2rXs=,iv:PrM5duaPf+fFzTFQCQnwwyHV/Bez5vRyD9EyF+W6Ez8=,tag:YmumGNpYtV9DFNN7w93Uug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
