apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13zy8tnl795dry8956zwaa9czept9erhcz6cvrup8md4p0s9465jq83mnp9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUzk0dWY2dkRrNW9JRHVL
            MVh2aEJrWXNOWkxObk9wNG8vN2o2V3ZPMUUwCnZWcXlIemJCZjZBcUxzQVZHWUNq
            RUM0OVJ3TWxLVmxnRWVaL2hobStlcjgKLS0tIEloNzFaaVo5d01FaFJuS3pQbTJO
            b2htK1lqQnFXN1lkYU9xcDhIZVdoWTAKKwo7txfSQJz0cqDQHsLk8/vl9KNM4VyF
            KzEL8jHMs/N48wmY+aNH0ejcDIhneeO/yunYM/TASjKc7OI+RpdT1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-28T05:28:21Z"
    mac: ENC[AES256_GCM,data:lvNDT1Q9FmGfAknlTbNEQefIzeNPPvovo8JX0ogWANXUn15uPd2ImLvOowc/l+Xh65bpjrhZDlaJEHx+oF2Tp4yyirrNf/qSHWxa1R8VK5PnIuaeBILOWlp8ovmzvnTvYDa6DqCNWqsqpQ5uma1EwMp+GnexgbayR8PLbU2lO5A=,iv:nnj8ouhxf/ikqiZPNTjxmhDaL/JfpcM8MYeKlk4eAtA=,tag:15MYSr8NSAN4S1s/1IroLw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
