apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:inxGe0NvavRA5IOp5ckxtwqy57jjx2wJO5Radw5KmC4dkQpoFJ7nUw==,iv:yccLVZ3bTXbbveQ9GtcYj+OovBPvMyiCE/BwK9TJG+k=,tag:6IxdhQ+zqmYOiAzVUpT9ew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13zy8tnl795dry8956zwaa9czept9erhcz6cvrup8md4p0s9465jq83mnp9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUjI1UlN0bWVjMVhwdjAv
            SG5yRXNJdW9pWDlYSE5Kd1gwL3VwamxSb0VvCktGclVpQU50bGY2TE1BVTlRRVl1
            cmZHbk8yUFNFUS95cVI2YzZtNDJ1VHMKLS0tIDVwV1pMblI5Q2hJWnJZNnJ0aXNY
            VTNMa0VTSWM2dHpQQXpLWU11WDJSYWsKTrKmQDq5lzqGjlNIlngyo0r2PJBI1IjG
            XropNHvfvowGn2LALBUeqf4kIFMp7hMVXLLKFYMKBnwRZLDZTkdiwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-28T06:04:13Z"
    mac: ENC[AES256_GCM,data:d+vxwt6gK1LNseCudpVwfZDUewtNARwuLx1AWEdVhTWGMEy3IC5qsjIEw97mtt1af41rX5woIO9mJegFvGWEIECkbt8JqUoWSFmccXkVzD39Qzpdjfoud8bwJK4BbyDGOe8Ui6WUGG58UzrcmRgVSnmx9hDZG6BHBcMGwZ8QfWg=,iv:nBtcolF9c2VDzaxe6WGwHpD4lrQFG5C+1Q9wx4DsLu8=,tag:QRZIqtKJlFiqwB1/hBiE8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
