---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ombi-config
  namespace: media
  labels:
    app.kubernetes.io/name: &name ombi
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 10Gi

  storageClassName: ceph-block
