---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: readarr
  namespace: organizers
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: readarr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        READARR__API_KEY: "{{ .READARR__API_KEY }}"
#       READARR__POSTGRES_HOST: &dbHost postgres-rw.databases.svc.cluster.local
#       READARR__POSTGRES_PORT: "5432"
#       READARR__POSTGRES_USER: &dbUser "{{ .READARR_DB_USER }}"
#       READARR__POSTGRES_PASSWORD: &dbPass "{{ .READARR_DB_PASSWORD }}"
#       READARR__POSTGRES_MAIN_DB: &dbName readarr
#       READARR__POSTGRES_LOG_DB: readarr-log
#       READARR__POSTGRES_CACHE_DB: readarr-cache
#       INIT_POSTGRES_DBNAME: *dbName
#       INIT_POSTGRES_HOST: *dbHost
#       INIT_POSTGRES_PASS: *dbPass
#       INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
#       INIT_POSTGRES_USER: *dbUser

  dataFrom:
    - extract:
        key: readarr
    - extract:
        key: cloudnative-pg-superuser
