# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: external-secrets
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:zcFc+CXxeXvBMDV4oIsxIxg6KN5vK7GDNHIpu/aI390+2tXSqsX4elCcpGfJlNbk7m1gupECu/ggggls4eKdJROtB4FrNHmCdWBAfh1+utyBKPKwIongskSxavK4VRrqFNjclXQ+wL3glYh4d/lsbKFw+c7IiBi077UwH6Weh1LfDJiecsDDLcmyDNqiQQ==,iv:9YKkIVkuh6ZrGR6zHChMhEfaK4umsFwguyZ/i+LBbYY=,tag:MK1PkCMXPCZnZ3WceCUo3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13zy8tnl795dry8956zwaa9czept9erhcz6cvrup8md4p0s9465jq83mnp9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2azBZT3dqK1RZeEhWNXZy
            RkdETzIwdDdNMWZQNHFFUXBBM29tOXFWRmtRClY0czREeURGTm1oNkRxVmVVS1VT
            SzFFQnEwSWVTcVozNDRXMkp5R0pqS1UKLS0tIER4OUN1ck9CQjFrS25ieHNDS29a
            Rnl4S0dUMURqTjBEVGdtbzhmWGM0NkEKXFn6XR7XYNepHLnSy5FiBhFhjpiL+WbZ
            5EmIwrARWDtkYsATLnRrxH4QG9PxDmv7QedGoD9F9dLXmdL+Lv/NEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-28T23:26:02Z"
    mac: ENC[AES256_GCM,data:BjAVHeR7yGCLVNAZ7/hxTJeq682acrO0ZtPaAXAG96Lv5ttzqFjcUf9N9FVPCuhTxYdvdGt/kUR1nAIyt7rVQr46YiwqWdPRWsivHam4ksE5qUkwmphM9wHu1tnLxO29n+L6KORqdQ4m3PwooSKp/m/fhtj6rDGgdcb/oSuke1o=,iv:axW1VpnJxZrU/RgevD2kQqgLsWHu8UkCLTtf3SSsmmI=,tag:o0HYoPMBXosB99muc2y+5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: external-secrets
stringData:
    token: ENC[AES256_GCM,data:GQt5LOdcKVYojcgE2Ul5NjggnDgcIH0ZAHy9dzWlGsGxsPhSSSAcYYNGRlPx17Px4HUFQqf5fuWzBdidM2fzzRzvxeTyLs7RIsypcFURUYcSLareY1uObtNdngKytVqw0AsT3U12eHaUDS4os8hYcDPdkZPkMB8O7tDDuZfxFLKOR1mWuD/OnVK0E78BRrDGGLENIG2csEIL4DB5437XzlHHjw==,iv:7WYYrD7d25WJ7F+dC9I06UxsoyK2Z5HoUlyG3ldypAI=,tag:aI2AZ+TJr9H317MGJKxaZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13zy8tnl795dry8956zwaa9czept9erhcz6cvrup8md4p0s9465jq83mnp9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2azBZT3dqK1RZeEhWNXZy
            RkdETzIwdDdNMWZQNHFFUXBBM29tOXFWRmtRClY0czREeURGTm1oNkRxVmVVS1VT
            SzFFQnEwSWVTcVozNDRXMkp5R0pqS1UKLS0tIER4OUN1ck9CQjFrS25ieHNDS29a
            Rnl4S0dUMURqTjBEVGdtbzhmWGM0NkEKXFn6XR7XYNepHLnSy5FiBhFhjpiL+WbZ
            5EmIwrARWDtkYsATLnRrxH4QG9PxDmv7QedGoD9F9dLXmdL+Lv/NEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-28T23:26:02Z"
    mac: ENC[AES256_GCM,data:BjAVHeR7yGCLVNAZ7/hxTJeq682acrO0ZtPaAXAG96Lv5ttzqFjcUf9N9FVPCuhTxYdvdGt/kUR1nAIyt7rVQr46YiwqWdPRWsivHam4ksE5qUkwmphM9wHu1tnLxO29n+L6KORqdQ4m3PwooSKp/m/fhtj6rDGgdcb/oSuke1o=,iv:axW1VpnJxZrU/RgevD2kQqgLsWHu8UkCLTtf3SSsmmI=,tag:o0HYoPMBXosB99muc2y+5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
