# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: external-secrets
stringData:
    1password-credentials.json: eyJhbGciOiJFUzI1NiIsImtpZCI6InhodHR2ZGh3ZTJ3N2NtY29lNjQ0NmZhajdhIiwidHlwIjoiSldUIn0.eyIxcGFzc3dvcmQuY29tL2F1dWlkIjoiREpRM0dIVEhUTkM0RFBHWEVGSU1QQlJaQ0EiLCIxcGFzc3dvcmQuY29tL3Rva2VuIjoiTlVQUjZITV9uRTdVVTM3eXBMR1NsaVVOelN5TF9VN2YiLCIxcGFzc3dvcmQuY29tL2Z0cyI6WyJ2YXVsdGFjY2VzcyJdLCIxcGFzc3dvcmQuY29tL3Z0cyI6W3sidSI6InNkNHZlNnhheHM0b3R5a3g3a2JxYmN5dTJlIiwiYSI6NDh9XSwiYXVkIjpbImNvbS4xcGFzc3dvcmQuY29ubmVjdCJdLCJzdWIiOiJSNE9FV1hERzNaQkJGUENMS0k2R0JONzdLSSIsImlhdCI6MTcyMjIxMTg2NSwiaXNzIjoiY29tLjFwYXNzd29yZC5iNSIsImp0aSI6Ink2enFyam9ybGttZ3d4bmM0MmM3NmdsdW9tIn0.KvxWRZuBK5D3pw0IllcUnOefvOhNPYPRc42dJq32LQe0HRx9oLoLcbKoUQcyRQIK___6LC7qWt7yx_xqADWlHA
---
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: external-secrets
stringData:
    token: eyJhbGciOiJFUzI1NiIsImtpZCI6InhodHR2ZGh3ZTJ3N2NtY29lNjQ0NmZhajdhIiwidHlwIjoiSldUIn0.eyIxcGFzc3dvcmQuY29tL2F1dWlkIjoiREpRM0dIVEhUTkM0RFBHWEVGSU1QQlJaQ0EiLCIxcGFzc3>
