# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: external-secrets
stringData:
    1password-credentials.json: ZXlKaGJHY2lPaUpGVXpJMU5pSXNJbXRwWkNJNkluaG9kSFIyWkdoM1pUSjNOMk50WTI5bE5qUTBObVpoYWpkaElpd2lkSGx3SWpvaVNsZFVJbjAuZXlJeGNHRnpjM2R2Y21RdVkyOXRMMkYxZFdsa0lqb2lSRXBSTTBkSVZFaFVUa00wUkZCSFdFVkdTVTFRUWxKYVEwRWlMQ0l4Y0dGemMzZHZjbVF1WTI5dEwzUnZhMlZ1SWpvaVRsVlFValpJVFY5dVJUZFZWVE0zZVhCTVIxTnNhVlZPZWxONVRGOVZOMllpTENJeGNHRnpjM2R2Y21RdVkyOXRMMlowY3lJNld5SjJZWFZzZEdGalkyVnpjeUpkTENJeGNHRnpjM2R2Y21RdVkyOXRMM1owY3lJNlczc2lkU0k2SW5Oa05IWmxObmhoZUhNMGIzUjVhM2czYTJKeFltTjVkVEpsSWl3aVlTSTZORGg5WFN3aVlYVmtJanBiSW1OdmJTNHhjR0Z6YzNkdmNtUXVZMjl1Ym1WamRDSmRMQ0p6ZFdJaU9pSlNORTlGVjFoRVJ6TmFRa0pHVUVOTVMwazJSMEpPTnpkTFNTSXNJbWxoZENJNk1UY3lNakl5TWpNMk9Td2lhWE56SWpvaVkyOXRMakZ3WVhOemQyOXlaQzVpTlNJc0ltcDBhU0k2SW10dmEyd3lORzk1YkROMmRESnVkVzVwZVdoamMyYzNjblJsSW4wLk4wcUpLR2RXanIzNG1UT2JQaHFHUVFBcUstSVRET1JoNG4tV256UzdQU0g4SmpLZ0pNbU9JRjc4OWpZM2RYMzlEZWtfa2d4ZUsxOEJWcUdyS3hnLWRB
---
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: external-secrets
stringData:
    token: ZXlKaGJHY2lPaUpGVXpJMU5pSXNJbXRwWkNJNkltbHphbnAyZG05cFlqSXphelJuWXpaM2R6ZHFOM1ZrWW5WNUlpd2lkSGx3SWpvaVNsZFVJbjAuZXlJeGNHRnpjM2R2Y21RdVkyOXRMMkYxZFdsa0lqb2lSRXBSTTBkSVZFaFVUa00wUkZCSFdFVkdTVTFRUWxKYVEwRWlMQ0l4Y0dGemMzPg==
