---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vpn
resources:
  - ./helmrelease.yaml
  - ./externalsecret.yaml
  # - ./networkpolicy.yaml
  - ./../../../security/authelia/app/externalsecret.yaml
