---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: loki-secret
  dataFrom:
    - extract:
        key: loki
#      rewrite:
#        - regexp:
#            source: "(.*)"
#            target: "minio_$1"
