---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: loki
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        S3_BUCKET_NAME: loki_1
        S3_BUCKET_HOST: "{{ S3_BUCKET_HOST }}"
        S3_BUCKET_REGION: us-east-1
        S3_ACCESS_KEY: "{{ S3_ACCESS_KEY }}"
        S3_SECRET_KEY: "{{ .S3_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: loki
#      rewrite:
#        - regexp:
#            source: "(.*)"
#            target: "minio_$1"
