---  #
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app loki
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: 5.15.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 5m
  maxHistory: 2
  install:
    createNamespace: true
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  values:
    loki:
      structuredConfig:
        auth_enabled: false
        server:
          log_level: info
          http_listen_port: 3100
          grpc_listen_port: 9095

        memberlist:
          join_members: ['loki-memberlist']

        limits_config:
          retention_period: 14d
          enforce_metric_name: false
          reject_old_samples: true
          reject_old_samples_max_age: 168h
          max_cache_freshness_per_query: 10m
          split_queries_by_interval: 15m
          ingestion_rate_mb: 50
          ingestion_burst_size_mb: 1000
          per_stream_rate_limit: 5MB
          per_stream_rate_limit_burst: 20MB
          shard_streams:
            enabled: true

        schema_config:
          configs:
            - from: "2021-08-01"
              store: boltdb-shipper
              object_store: s3
              schema: v12
              index:
                prefix: loki_index_
                period: 24h
        common:
          path_prefix: /var/loki
          replication_factor: 3
          storage:
            s3:
              s3: null
              insecure: true
              s3forcepathstyle: true
          ring:
            kvstore:
              store: memberlist
        ruler:
          enable_api: true
          enable_alertmanager_v2: true
          alertmanager_url: http://kube-prometheus-stack-alertmanager:9093
          storage:
            type: local
            local:
              directory: /rules
          rule_path: /tmp/scratch
          ring:
            kvstore:
              store: memberlist
        distributor:
          ring:
            kvstore:
              store: memberlist
        compactor:
          working_directory: /var/loki/boltdb-shipper-compactor
          shared_store: s3
          compaction_interval: 10m
          retention_enabled: true
          retention_delete_delay: 2h
          retention_delete_worker_count: 150
        ingester:
          max_chunk_age: 1h
          lifecycler:
            ring:
              kvstore:
                store: memberlist
        analytics:
          reporting_enabled: false
    gateway:
    # enabled: true
      replicas: 3
    # affinity: |
      # podAntiAffinity:
        # preferredDuringSchedulingIgnoredDuringExecution:
          # - weight: 1
            # podAffinityTerm:
              # labelSelector:
                # matchLabels:
                  # {{- include "loki.gatewaySelectorLabels" . | nindent 12 }}
              # topologyKey: kubernetes.io/hostname
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: 'false'
        hosts:
          - host: &host 'loki.${SECRET_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    write:
      persistence:
        size: 10Gi
        storageClass: ceph-block

    read:
      extraVolumeMounts:
        - name: rules
          mountPath: /rules
      extraVolumes:
        - name: rules
          emptyDir: {}
      persistence:
        size: 10Gi
        storageClass: ceph-block
    backend:
      persistence:
        size: 10Gi
        storageClass: ceph-block
      extraVolumeMounts:
        - name: rules
          mountPath: /rules/fake
        - name: scratch
          mountPath: /tmp/scratch
      extraVolumes:
        - name: rules
          configMap:
            name: loki-alerting-rules
        - name: scratch
          emptyDir: {}

    monitoring:
      dashboards:
        annotations:
          kustomize.toolkit.fluxcd.io/substitute: disabled
        labels:
          grafana_dashboard: "true"
      serviceMonitor:
        enabled: false
        metricsInstance:
          enabled: false
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
      lokiCanary:
        enabled: false

    test:
      enabled: false

  valuesFrom:
    - kind: Secret
      name: loki-secret
      valuesKey: S3_BUCKET_NAME
      targetPath: loki.structuredConfig.common.storage.s3.bucketnames
    - kind: Secret
      name: loki-secret
      valuesKey: S3_BUCKET_HOST
      targetPath: loki.structuredConfig.common.storage.s3.endpoint
    - kind: Secret
      name: loki-secret
      valuesKey: S3_ACCESS_KEY
      targetPath: loki.structuredConfig.common.storage.s3.access_key_id
    - kind: Secret
      name: loki-secret
      valuesKey: S3_SECRET_KEY
      targetPath: loki.structuredConfig.common.storage.s3.secret_access_key
