---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: influxdb
  namespace: databases
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: influxdb-auth
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        influxdb-user: "{{ .INFLUXDB_USER }}"
        influxdb-password: "{{ .INFLUXDB_PASSWORD }}"
  dataFrom:
    - extract:
        key: influxdb
