apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:vOzsOE/yY6tBqQw=,iv:m1/m2envx1a6iE9EWPI2SKLs5+y5VwdNVptQS5eK2UI=,tag:AxS5iusHqUkLMfEKgD5ibQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:q0Yi2/UtfXGZn0+xXJbdMA==,iv:xef7iqJ2IMKpGx7bDMMF0nDmNAwnn0iZWzICJC4yyWk=,tag:+Oj3eVh1VUe2DDB2tVnbQg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:bgKiJHzk6mUCSkgAwTGFKnoWlyMzpAnaOCeabiyu6KefpAW+,iv:YggHI8NsK4SNJEYRCgxoqqKFFBNjnW0WE63JPxN9EjU=,tag:b7/SvCuX4xBQDqpaLCrfcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17mejdfq9mpp3uhqenmtrhuxs598atx33telpakcwcp59wzrg3q6qcl34w0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTG1IbCtyVTJHdGQwZ3Yv
            UXI2TlV6ejlzbnltT3I4R3RncURWYWkzUFh3ClpxNVZxUGVGa3pwRzhhS3FYeVJ4
            dWJ5bWhHdm40cTdjelV5UlpyMjFmcTAKLS0tIDcyZDdKbkhmUWFQMWFVT21PRnJ4
            VkVFZStobk5xTDR6WDd0QTN3Ykc2RUEKRshnpmFXGRDmbE+lOjdr8bxlCW4Trl0f
            CiAfKYSRnUqYNQjEvUiey6DCUXFK5Xlw/dG4HBTpxxuvHHmAov1YZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-27T03:13:41Z"
    mac: ENC[AES256_GCM,data:xE7lADhAH6GqNnKxtVEPGNC6/cPGQ2+1rIGFAvrmc6435ULFKQg38YlWjVnRbZBdtkMllaS6MUL8Ql9lYk5Pyrm4JnShlBXL3wLAXoPsNRdASKB0sp983dvwoXDfdWqBnFKCDUSNVpBPodiWdQBUmye9cmKoO87VY4R134XQF/w=,iv:YiYmx/IaQwB6mr6XLVw6esM8+Ls6Xb5OcjAFjpjWgG0=,tag:A6v1ttiY8UXJL6KARDQJbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
