apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ""
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:m+YriF80apMfEodcTALJ0g==,iv:RXG9dGVtIWvnan02KYBV/TyS9ovkvLslV8a/VfvCVjg=,tag:K54o0gPqDBX8k253+ODNXQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:hhp55HXylMVwJX9OmcyItELi6rbYB29Vlbzh5B6wVASCG73V,iv:0QXHO2Xbr+uECb9+4WIHhzNDOeopfihx9lAfNPW/KYQ=,tag:FC4m/nzgdWcG+akBBgqA3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13zy8tnl795dry8956zwaa9czept9erhcz6cvrup8md4p0s9465jq83mnp9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZitMNnRRR0dVQ0FwbjlJ
            TThBOHVYNDFJZEZPK3VzVWZtSFQwdit3eW5rCitEQTlUZkU4bHBBTTU2L0pWL2F6
            WEVkSkNWUHB6U0hoOWlQQW02MkdmTTQKLS0tIFhyZHp1cUwvWG8zRkMwMHduMjQx
            a3dtb2IwSFdLdHNRQXV0QWp2OWlJZkkKyHscTYmypCReOg0zh4CS8+S2rhWUktqN
            ESW1tqokVEgINdJ6reE5MMK3YPyukmzx05ZGt8uJXCj0/fYnPbo3NA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-28T07:47:26Z"
    mac: ENC[AES256_GCM,data:1k0pFhufDWA3ayQD5G/+EvonV6BeugRJqjgVduXjj1fLu09O0zNVLMtjIVDJXJV4orqcggdMhiOXfJtaEVa7I5n1QslNcX97dQPPIxOqMn2uD1uxbhr7MAsu6dTsVhFLPxbFhPdMte2kadWKtyC3aygArSnBrdD43eZUJ1D10DY=,iv:A/nv6Mh868s+cHSCeeKp+nSEs5wOHpTExCXaa7t69sw=,tag:apmNPTJKry0kH01fVAP+fg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
