apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:sHrq0sVWkvUDDCs=,iv:zSWxYoHR+uBKpmyYgH7TJJR4G5Zqh8dQggAByIV+zsE=,tag:BWwHvxj/k/gkKLJguJTPCQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:0eCE4Oe2bJ60jPznhFVuAw==,iv:H/c4moGATj/o4bJgKALgI/r7OUBVU0nyJHkgeT7dFHM=,tag:kSCt1G1RZGkW97p2OQUUPQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:OTlo6vY/sEBU8qCQJkMHXXc6qjwsNxJ6w9vKWM4wvfQ+Qlis,iv:8mm6W8O+hvTT9ge+cswrLJcX07MUBUDfF/SdW76fD84=,tag:fJL3VRy1TM1wDhwZprTy9w==,type:str]
    SECRET_DOMAIN_CC: ENC[AES256_GCM,data:FkkhoPYK0BoXvw==,iv:/0SAjzYYO1oOHlE+oBsEef6Z2wYRbU6Er1PBxm8KA5I=,tag:rmb4Tcp7GguZYtvlQkpjTw==,type:str]
    SECRET_DOMAIN_CO: ENC[AES256_GCM,data:u+3fET+zjdyI5g==,iv:48UItu9dw+o7USuCJgJHF5mZaHiHw3dZccNYFDIOYaM=,tag:5Cj8MNsHjOzPYYbOvB0W/g==,type:str]
    SECRET_DOMAIN_TV: ENC[AES256_GCM,data:khpKLAEny+eCTQ==,iv:1Brq9U3TMim2LQmzpkr6B7TKh6E26sfFcXcVJ6LE7NQ=,tag:fj6k2Ic+iznBKXP1z+ERZg==,type:str]
    AUTHELIA_SENDER: ENC[AES256_GCM,data:YTduiscveyIfuqxTUiQ/t0KBvsBvtsSc0LIr,iv:JcyNQ5MXOD2wzqwu4MP9EDBbH/5V2VCa4zW5Iex8cqM=,tag:HZ2XMAbTfat38vYwsnhQyg==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:so+kU1V4MTQ5PFUl7zkmnw==,iv:Oatz+5Np5cGE5PrKML/zsbWL53J6rlx+8WsDzDK0Y34=,tag:o1zPax06xmqR9TXSD01v4A==,type:str]
    NFS_SERVER: ENC[AES256_GCM,data:3J18632DYlcBYQ8=,iv:MTtmuJ6dRhN8u3AzyNR4z2Q5vHt/TTzNkxk3tpOEevQ=,tag:0Ym7/ZAf+qVROVObcWNqBw==,type:str]
    NFS_DOWNLOAD: ENC[AES256_GCM,data:tWVdr2vfOHuw5oxxJwsAHvU=,iv:dquoSprg9YtgyiOzLYUTSWbQ+rv/+5ETaz0K5bRdpP8=,tag:OUiOdlUipWo18xbLmY46iQ==,type:str]
    NFS_MUSIC: ENC[AES256_GCM,data:gDk4shEUayxDoXI9mEQ=,iv:iQCATreoFWbKd8/Gb4Xj6IeC4LiYjLSg8RE/abm99f0=,tag:IuEHhq3L+1aAYTJloMAXwg==,type:str]
    NFS_MEDIA: ENC[AES256_GCM,data:iiy6H1QBkR6EP7x2W1U=,iv:Dnu5M/t+K7lPdNNPSPbCwJoQvg49XaYtENVHQ5OyjGI=,tag:sT5JPW6haID8m3JCehprmg==,type:str]
    NFS_BOOKS: ENC[AES256_GCM,data:TjFkkHmjVzS3elyqRjc=,iv:oHr0XW30LnRb/3sGUMDRPYiSud74JgePNbHrpSmYDI8=,tag:Kq19xr93v7FRfID3s7a4BQ==,type:str]
    NFS_KUBERNETES: ENC[AES256_GCM,data:aysWzf8Ti468MPjazhJjngDTOQ==,iv:Fy8SGAUzhHVeEj0n4PsXpZpIe6tqdWPkVL/YVi4ABY8=,tag:1xP6bHMYBXgAXzyMl6Wusg==,type:str]
    NFS_CSI_VOL: ENC[AES256_GCM,data:JU1PJhnk3x6kZM9V2A1Ep+vPzQ==,iv:evYyWKwyd20BBL0fJOglzvfrHtsNTmBRhn5cHO2rsz8=,tag:TA/2HRtu0iKsD3QhjpvYTw==,type:str]
    NFS_SUBDIR_VOL: ENC[AES256_GCM,data:9FxLMOLw2LaQHU2SZDug42JoV9Akbds=,iv:1uRPLkGtdzmmqZiDyCmAdWDhL9BIGISmiLiMpE2gVVA=,tag:PvIKay3P8q/LydCX02+IHg==,type:str]
    EMAIL: ENC[AES256_GCM,data:yf3IaErmNXTRs1CNm6V1rw==,iv:3G2myuuGvetWqzj85F5xh7u1RdOzXEYjpwMcIGwy9y4=,tag:Th50mOkLWoGM2lNHOfXGnA==,type:str]
    LONGHORN_BACKUP: ENC[AES256_GCM,data:QdqnUU6PL+ZPkk2qmDAMy9Wy1TmvuzjVoyMqJZnmdLb8qfM=,iv:wPOuRcT/sLkz2j0oChQYj1zQktEQ7nnipj/5acdp/KY=,tag:JbfzyvKdNGgb4tzWp1Akqg==,type:str]
    NETWORK_K8S_CLUSTER_CIDR: ENC[AES256_GCM,data:/LacHp29OKNV4XA9,iv:jPZhWGDbqJ1JYebR7FwjOg98E4KRgFyPp+syR8cXRMs=,tag:vxbFOpmV92K9IHNOXPJ39Q==,type:str]
    NETWORK_K8S_SERVICE_CIDR: ENC[AES256_GCM,data:ShVjNTzIs6c2da8p,iv:hsTEZOq84+XQiuFVn2ejw6oW2x/bYTciGpUyIFvzHlE=,tag:S4aUM57//aEs2SUjnJ5aHQ==,type:str]
    SECRET_WIREGUARD_PORT: ENC[AES256_GCM,data:fTlfbF4=,iv:sTkeKF9mKfuMVp11fyN7XN/3YPmHaqNjgOVS0sUc4FI=,tag:rzFIez4yGRfnT8krT5WGiw==,type:str]
    NETWORK_SERVER_CIDR: ENC[AES256_GCM,data:+K2c1ot02BOIRQ==,iv:bKLveESTa3epU9oZSi86cXZowXn7KO8BN8DhSuW69HI=,tag:OSqExpoxl9NFsrhkEw3X2Q==,type:str]
    WORKSTATION_CIDR: ENC[AES256_GCM,data:+/56E0vBpRhnWWh8GgY=,iv:IH7zCuHJSSTVwyzdu5jcvnNC24CI8a+yYt8TEaQGJGk=,tag:R8Q9KtGN1hhE31OtGZMPKA==,type:str]
    SECRET_PASSWORD: ENC[AES256_GCM,data:PbJypOgAMME=,iv:0tFVzPmyooXquwcGaRH5QdgZpzmL4LIv1vpLOBU4pKE=,tag:ztb3e7ih1fDwNdWo1EaXeg==,type:str]
    SECRET_QB_USERNAME: ENC[AES256_GCM,data:WPkyIr4=,iv:MeyM4FqdKLIfBFsQbsLqEN+QSJtoN1C5dGZUJMAmfp0=,tag:GF+6dIxD/8Sd+HhscNv3wg==,type:str]
    SECRET_QB_PASSWORD: ENC[AES256_GCM,data:TaKx+forWX0=,iv:OLKOI10UjQHGhYyxHhpivev/eCTXGmDWkLhSk4yM2Xc=,tag:v22ScKYaWASExzi4t/J/Ow==,type:str]
    NFS_MINIO: ENC[AES256_GCM,data:uQylHJh9avR5T6GWc2A=,iv:L5cEH+agklmpWlfUsegM82dwXoypm6TNJ6E8EwURbD0=,tag:YdJ9ZuI/xRlpeNafP9cF1g==,type:str]
    SECRET_MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:8oMAQAa8aig=,iv:h0zzPCR7KCI03JDuBOCIVs5KO5Fv2pwKwHcd+qBMRBc=,tag:sz4HQPSl4x40Z/gpHuzr6w==,type:str]
    SECRET_POSTGRESQL_ROOT_PASSWORD: ENC[AES256_GCM,data:oS+4Nm04QFQ=,iv:RUAl/co2jO6WmMUUkBqpezFd2csvZ1B8sWsRcTyNfcg=,tag:E3pc8v7UKRqTYqndHvKspw==,type:str]
    SECRET_KOPIA_PASSWORD: ENC[AES256_GCM,data:22kZLQ354eg=,iv:FtQGQFdqBxC3HtKA7+GrBpbnPSwWUmBYOjzGYSe1rzY=,tag:uD+A8lLzIX0yMSoXUACkjQ==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:E6hpmpe5655MxUAeLpremmyBHNPE3PjXkugIIyooN5u9PbGEB+ysCq9PdtBWdcKuj2BYa0HIDblcBJCvfOD7NoAykALZzWM=,iv:iEXaJU6vZvbSqWfDAcfs1uZH6f9ZE5HRdFpBgiaj3Mc=,tag:tFw1oRJjVdnNcHJx6Mfhlg==,type:str]
    TZ: ENC[AES256_GCM,data:QVTDsaDQPucT/V88OMGFuqJcsJ0=,iv:e9yGNhB5eT7BmNw5S0XCxBmIl/dx5WzNsraih5qbjJQ=,tag:q7Xm3Nr9W55xtvW6+vqKVQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL: ENC[AES256_GCM,data:KMGZCAzSGgSiMq2S1ZgqeAuDgch7wv99nBOvagclg3nzDZmNxakf2fkv2BGiVAijKQODTwk=,iv:cTlIfPgIppGBirm1kt7mL9iChiMTR6pW0Dr3eeHqcNg=,tag:pASR7A623b9lKxTh57YS4w==,type:str]
    HARDWARE_DOMAIN: ENC[AES256_GCM,data:gNk+OgNOn0WzVQ==,iv:cIAYbMjU+u/gNadVJKmhe1KyHUjq/ApSv+gwY0ZkpPE=,tag:LXmBqKvC+hDNf3GyoHgrRg==,type:str]
    CLUSTER_NAME: ENC[AES256_GCM,data:BJ+1iM6owA==,iv:QElPvX9sc/l5EZO/WaVWdB1oJ9JqzgwcPDrYcWJo8U8=,tag:2kauoEpGQ8Sf11IH1UEB7w==,type:str]
    VNC_USER: ENC[AES256_GCM,data:V2twAhQ=,iv:zfgMOIwjksCI+UTVNZt3Ou3jwToFgj8RV/Y4Ixm5eXQ=,tag:tGlI1137tpbkBJuvYVxa0g==,type:str]
    VNC_PASSWORD: ENC[AES256_GCM,data:WuNCvdvGdg0=,iv:qjw8x7fv27fp9tHGQOK6mwevF6+iDIzmeeE5tf4uFKw=,tag:taoUIgmWlTvrJK6Bu5OiEA==,type:str]
    SECRET_BOOKSTACK_DATABASE_PASSWORD: ENC[AES256_GCM,data:ZTFr3CxkalQ=,iv:LtEDN31M3ej60VB72bCGURdYLcOuW0KAzoe3pepJMYs=,tag:AN9gZ5oXqElvanqpD7slVw==,type:str]
    SECRET_RANCHER_ADMIN_PASSWORD: ENC[AES256_GCM,data:pXS5K/fBCHU=,iv:KNHYlh+b63nxxJQMIz5jtIzdoxMvUZIw6BOpqh5+bi0=,tag:F2CYinWu3kBsgAOY7ybbuA==,type:str]
    INFLUXDB_ADMIN_USER: ENC[AES256_GCM,data:Z/dlheY=,iv:wDwI5I1XBsxwcO75iqHSw+Ohliu1n7vd30OofMxpMJo=,tag:KlTc0Eg+D1SwSqjL2ucShA==,type:str]
    INFLUXDB_ADMIN_USER_PASSWORD: ENC[AES256_GCM,data:5hZHWUFUYx8=,iv:aXvh1p3QmzIDt7D6l7h1jl/5cQmabWzpYPyOrXB/YRI=,tag:SDm5c+VjpZxBqCOfaFxAsw==,type:str]
    INFLUXDB_ADMIN_USER_TOKEN: ENC[AES256_GCM,data:fc4kHDOSpTx7XQ==,iv:0kXAul1Y1FCHF/5npLoXhLcnUpNmh9Nk2B8z4g29fIo=,tag:fjBVJXMw/UsRu+kqKDkwUA==,type:str]
    PGADMIN_EMAIL: ENC[AES256_GCM,data:8tw7v4x3xQ4Dxk2wu9NVGg==,iv:NSCBcmBycDFk+mVMB2Scp2QOSL8hDy//WKSQ2mU815Q=,tag:fQ8uWkQHMzNeKHj08Qo4dA==,type:str]
    PGADMIN_PASSWORD: ENC[AES256_GCM,data:eOpiOLaHN7w=,iv:Y/7wPh5f4FDusY2ph+gcW/rSAvtbXu99XNsA9MGiwGA=,tag:/vKIB3Hgds2X6XxGhJasUw==,type:str]
    AUTHELIA_SMTP_PASS: ENC[AES256_GCM,data:aEuvFFKrAe9t2YjyTeFXWQ==,iv:LWOB/prXk8vMEjd8ZO2T7vAZ+DlOodR/9JtYQZy2R/4=,tag:cqqUHhvldFyo+GLk+LsKaA==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:4eMtW5QnSy+PczE=,iv:wa+GsboNlN6MbUJtlnXj2pvmED9kKdaSVmOHbLN04KA=,tag:lfKP2OJnVFwrS/8BpT2mMQ==,type:str]
    SECRET_OUTLINE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:8UWJDvyUUkDQ09A6F00R6CVbqNZKh7zkXdc=,iv:hT5pdtaTstP6DZ+syKE7S/RfnBzCjglq53Q+rioz7hg=,tag:vEkyQu3nUJ/2P0gbAU5e2g==,type:str]
    OUTLINE_POSTGRES_PASS: ENC[AES256_GCM,data:PiCxp0bFBc47hOzLvivXT8Ewp9vA7F5h0Mo=,iv:eb3aO6ycU9ucIcF9Pn+TEGl2zxgl9s+u3/AjcxcDN5I=,tag:lGEjErgvIKCk+V+p7by7rQ==,type:str]
    OUTLINE_POSTGRES_USER: ENC[AES256_GCM,data:asedRqNkZQ==,iv:0OzkxKJd9WdlL3eQLlKDJ5L9RyPHRAJWJE5EJDg7xuA=,tag:P4ye3nnX++aJrYrxdid2MQ==,type:str]
    SECRET_GITEA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:MX/m/GISyoTZxZYNYnxEa3lIwe58LiTW5kg=,iv:HSEEZVUxZYPTvulD5+1gDmlUwx/A1mE5A6NKPXu+NmM=,tag:eFbuOEJkJR4dYIy2l/0nyA==,type:str]
    SABNZBD_API: ENC[AES256_GCM,data:1uWLTpta8ss1Ybp8Av3smPjgf8qIdtl2eoplqSu6jd4=,iv:ngA5MfJxyzgqdtGZEsL/YK4AhdBpEStIwkAqafC0MGM=,tag:EzbTG3bLEVMqk5xP7m9Tsw==,type:str]
    SYNO_ADMIN: ENC[AES256_GCM,data:niuDZZPQZGg=,iv:uBnYWTHAuS+qd66S126d6+Bm+2SrtE1kZABiHa1RNyg=,tag:m2vjpuUoHMYoOaFR2ArpfA==,type:str]
    SYNO_PASSWORD: ENC[AES256_GCM,data:tUsEqdAjLs4=,iv:g64A6E3bF/PuxZhqjFu5iuFjAUxgxLR4xrWhn4ZeFLA=,tag:Rm0qxAPkKEkqj4XX89z2eg==,type:str]
    NAS_SERVER: ENC[AES256_GCM,data:17povpjngBNplEQ=,iv:4dYXZkvvy+apf1em3s8jtgTvHNGiMOa2FnOXCFtdRoA=,tag:1C7XZmMjULcGJKukuzagCw==,type:str]
    QNAP: ENC[AES256_GCM,data:L9uTiYJ83RDUkX4=,iv:GaGaCex+kGs9I5z4HNnsSjWKrij/MWY01K22JOvyZc8=,tag:wu5kjSaqJT2gjDQmAyEUjA==,type:str]
    CUSTOM_WEB_PORT: ENC[AES256_GCM,data:8pvwWQ==,iv:5/qA2WQwCvgxgXh1/qUUgNxeh0MdVYFz27RymVeH/3k=,tag:y8XOWfn9Of0YYpPGILCdfg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13zy8tnl795dry8956zwaa9czept9erhcz6cvrup8md4p0s9465jq83mnp9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSFB0RThKRzdWRTd2bW9y
            N0J2NG92SVhxWVNqMm1KcVJGRW9Gd1N3MWtjCjUrOXJlQXFsd0lUbmRpdkdBSkFQ
            Tld6OXpjaysvMW5Nb2VGTEluRXFHdFUKLS0tIG5HSXZrNSt0YW0yT1NESnNvTk5N
            MHFwL281UVYxaHFCaDJ2WEh3RHM2aVUKmwkcHRsKLHE9PiAb1HIXMh59yLoSBi9z
            nKFBxpgt1y+pE1mBfOvUohGl8t5HJhHGMFvAcGO22HU2aJykU+7kGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-29T04:55:03Z"
    mac: ENC[AES256_GCM,data:hyhsXK7KMJ7j0iz/jolnz9kXpi9L2HdBlsS4IwLxy7M7SVZFwrn7CWNhpmyVvQ68OZuNsjAwdUVNyGWXPBZ2J9S/oJrWOOZvnVV1kGk35Kfry7LCWrqrDjtKp/ZfbOhmf8bOcH6FnRG4rnEY8d1mj4fJbFEEKNl0z5AYE1kKZrs=,iv:9dHwek6InR4os1TVxX565LIDMthctwtKmnYDHPdBLoA=,tag:B4+9RTKKOb2q/flpK6ip4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
