apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:d+97qMgsWgltzyI=,iv:IWJBYVknINmcav4v6iW3hqJH27cTxEPjbsHxCdYj+f8=,tag:UtZTBTYa6cIEcC/RFYKx/Q==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:Pcl02fPigM0L+To1mo9z0Q==,iv:XVmnLyP1iBatAhpbnXKYRgK+MSf5dnuyUoWVppIF5nM=,tag:11hdF0Qqx1nDS8oarvNQmQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:b019a2ty5SUWqErRjB1YMqaQphnA5wu9UzwA8V3K+VBqkw/+,iv:x56ktKwS7QjMH+eyyy6p/6mWL4HYeCluZ8gQsw+VS94=,tag:fhpGi5ZBQ3kAO9fKpxnCZA==,type:str]
    SECRET_DOMAIN_CC: ENC[AES256_GCM,data:txdqOz1iUKHOEA==,iv:QmPyPI110TpSPA62f2rq6/f46VtBUs/3zAItaW5BEGk=,tag:7HZntefXmdMVuNabI0qr+g==,type:str]
    SECRET_DOMAIN_CO: ENC[AES256_GCM,data:2pixSQKglyRspw==,iv:gEAni7/zWKyRZHyPvqjYZ3l0UmAKwL4+aR95U9oKeQ4=,tag:u5pIaqvxb+rwVokN3mFAkw==,type:str]
    SECRET_DOMAIN_TV: ENC[AES256_GCM,data:1WAlWn7xPaWtRg==,iv:m0J9HgtKQhydRuzxTGTn/w5jhakCFofSrfWSheCVZCQ=,tag:IkKzrZV9XbzZRY7sD2E6IQ==,type:str]
    AUTHELIA_SENDER: ENC[AES256_GCM,data:i+7VUSZqIihQqebWKRydDb1Zby7CDbjsNT58,iv:ZoVUdgtjU2WbHPjT9tlc0GsSq28vH9HA5mcuZ/xM9TI=,tag:KxklsIELUnjVSMZ1Wxf/XQ==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:QfmvRTQG1jnI7Jx3CCYZEg==,iv:1rLBMrVN7sssk0PujflX0x3q+XdKeSZZinK95MB+sa0=,tag:rYh7fh4p5fpdFTkXR6MEZw==,type:str]
    NFS_SERVER: ENC[AES256_GCM,data:szHAqn6DhN3xozc=,iv:X42BTeWxEAlBVC1X6YJ/2eCIUgM7bfnS6+p3TiFcqp4=,tag:V9mGi4TrE46NqBg6h82dQA==,type:str]
    NFS_DOWNLOAD: ENC[AES256_GCM,data:X1CAovQVtCSz4OP0cEOoisU=,iv:AKbqLhJyj0Fm4iciuRnj6U8Km8qfFIxYjeHAfFQPNOk=,tag:qgMVwHew9MVYh4LYygKszg==,type:str]
    NFS_MUSIC: ENC[AES256_GCM,data:CrsOvlj9O3XD1JpZnso=,iv:zjE+9wjGHCXo5MNkm2hS0Una8A+/Tvtfpne1ZpuSo3E=,tag:WFpKKhEIz0wvD9buvB7f0w==,type:str]
    NFS_MEDIA: ENC[AES256_GCM,data:nA8nYSwKujJsWJJdr/k=,iv:FshH3rA8sXQfQe5Sa4kDPVZ1QW8kTfPiVCCTocC2f9E=,tag:owxQDT4hjAPi0vpQbxvFtQ==,type:str]
    NFS_BOOKS: ENC[AES256_GCM,data:jUG7mD9D7hS2+tpa/yw=,iv:Leoa+ZYdJ5OE7ajP95WtopnzHUIoJbpv+LsrsMKhh6Y=,tag:vsQWOAJS/nJG/keWrVyRRA==,type:str]
    NFS_KUBERNETES: ENC[AES256_GCM,data:V07xCUcJnktXk6pqMcskWgrjUQ==,iv:xjIbhye9qsZSpdWji8lrZU5C1pQpD7fVTcDPYdtkY/I=,tag:cwh5BMea0+1hGi1I9ArmsQ==,type:str]
    NFS_CSI_VOL: ENC[AES256_GCM,data:GgX8OiT/1YPeYs15FtOM8JrRXA==,iv:DcVwfORTgesylhhpav3YNm77RiQIsP+Pt8lhCuGrrn8=,tag:kDNxFc2n+sEhk9FUIgJ7Qg==,type:str]
    NFS_SUBDIR_VOL: ENC[AES256_GCM,data:hlbPTKSkz88h72eSzkmjoKB8ahbwWHI=,iv:Q5WwsLgIfOdXvoBEnQcz2jliT2UrjUZq8wVDRjs2HA0=,tag:LqELNmQvkpy6JeFvyUkaog==,type:str]
    EMAIL: ENC[AES256_GCM,data:+WjGTqWDjjVTxdVSNfxx0g==,iv:Hxmv3VBy42+dYOoDU8lENRcmZNFh88D1AlLLd+hlY18=,tag:BTs4kC4wjJzA09P5NeuHOg==,type:str]
    LONGHORN_BACKUP: ENC[AES256_GCM,data:t1Zl2h2hClPbMB7xoCMVkFcoh7tfdmLMcz5FNykKgmGTZHM=,iv:+fMeX9hvesmzhpGtDcWoEDBTkDk4QR3sVgNU4mq4jEE=,tag:AuHt5W8PyVfA1NCC9OiIdg==,type:str]
    NETWORK_K8S_CLUSTER_CIDR: ENC[AES256_GCM,data:6ZxHh2lPO3NZzKjb,iv:U+OrJBQY8784eIN6uhi5tLIr/stmVT2ASBJ/CfDtLpk=,tag:jOoS3d+tAxKGkb0EpnPTnA==,type:str]
    NETWORK_K8S_SERVICE_CIDR: ENC[AES256_GCM,data:uaI5seSyNcAz557L,iv:1gS7izXwKvKXpnagJ3baSeG0+kTdK/471WninKc03W8=,tag:Fj9pYK4w5DwIaYokwrgVoQ==,type:str]
    SECRET_WIREGUARD_PORT: ENC[AES256_GCM,data:tx0eJIo=,iv:T4/iYn5sBociX9xL1dVmEIrc4iIkVmv+DstboACsDrs=,tag:tBQxRhM3O5uhUVgGYuXYcg==,type:str]
    NETWORK_SERVER_CIDR: ENC[AES256_GCM,data:jrXQhGGikm7pzg==,iv:5CYlLx4+Beh3Rfp0UovOkDGGN9RPT63EH5ugkAvPbzk=,tag:wDI8JqFcW3JG9b/6cnzB8Q==,type:str]
    WORKSTATION_CIDR: ENC[AES256_GCM,data:7del82qVM+VedNQkN+c=,iv:qlJBhQS+sATe760JPkoxk/FRcIJYU1VViWpO5Q4SjmE=,tag:gJCFT5NuhHSfPCZxogF9zw==,type:str]
    SECRET_PASSWORD: ENC[AES256_GCM,data:xezuXLtaMuo=,iv:sc9kXi3389tWD5urgB5vxoALeNiHganacwn84QFTgws=,tag:wOqHtkuSCg/6pFBB9KqIVA==,type:str]
    SECRET_QB_USERNAME: ENC[AES256_GCM,data:+lqfNx4=,iv:pG7VItU5QZ43QOvYaNQl3DK6hfPnNnF/fZpiT06P8NU=,tag:6cpohqDHubrJe3wiyhp7jA==,type:str]
    SECRET_QB_PASSWORD: ENC[AES256_GCM,data:VeOfQZgvUJw=,iv:ZCb/IVIACjyRqxS9EYhFdw4mT0Gn6+GoOn/eaD9Pscw=,tag:bjhXo5kirGvn7evsDqXNkw==,type:str]
    NFS_MINIO: ENC[AES256_GCM,data:6gBCtHmD3I+CdQHVJeA=,iv:RH61jKGL0gOSSIB8O3on6XIbpr+UqXrY7/koQ/O1RWU=,tag:8FTIV5z2sY+NQf8+Pd1gJw==,type:str]
    SECRET_MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:NPwUnMgqNM8=,iv:Qy4GmcdMoqDJvNHRLkyhcbWhzl6APYi8tjvwik8JSSY=,tag:0Ic3kTe02y1AL8PZ+5w9qQ==,type:str]
    SECRET_POSTGRESQL_ROOT_PASSWORD: ENC[AES256_GCM,data:ZaYQ/3+ftD4=,iv:mI/+Mf5JYUnXxBdOUzzatItCsgHiuzApoyV+Uj+rKdU=,tag:7gHWX5V6nKMVKF0GRFnl9w==,type:str]
    SECRET_KOPIA_PASSWORD: ENC[AES256_GCM,data:Y+fptV4gcpg=,iv:FBYjI0crGGvQg0Q6IOPfFQzY4kuRJ7+hfnRfpcfAAnc=,tag:F/5ql22iyJwJkMpIRLMnAQ==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:wrvNjtzKbwBTzCF/o+erawTCO9eQ7PBxMOs=,iv:lCBC5ARPA22SHgvt69N6//V9VbuiwqvS69xVB08sWN8=,tag:WHyNAcbAefp+a8/nBTAwUg==,type:str]
    TZ: ENC[AES256_GCM,data:d0lILYkepWfD6zi7ouKanWqzeBE=,iv:yZqfb6XLOLdY2xq4PIhi3sTytlArqHUWBLSPFA8VClU=,tag:1bWxJmjgOaHG+GtFSGOYPw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL: ENC[AES256_GCM,data:QKeIIp2oW3yHbXpfkHSS+v7arX7pjgX7tpCL4Iw8XapxNp9o5uitmsbq8l2nYOvuMzZPinY=,iv:Md/A95eHinZ5VfCwpmi8n4VvQ2hV5lGZce0YbvoPuqk=,tag:hJWsETzHoBu9/jgych8DOg==,type:str]
    HARDWARE_DOMAIN: ENC[AES256_GCM,data:4WLsNxXHbV0xjQ==,iv:rbvMWXKoQpJCa3LI6StQOkZWdVWNf1MkmhTjhAl+rQU=,tag:PE1i+0iNIiUqLv9gHwMurA==,type:str]
    CLUSTER_NAME: ENC[AES256_GCM,data:hkxVJQ87FQ==,iv:BNaXMjNzaTzVnIg3TNfbfeRQN0hD4Tp5xr8BOvt9lS8=,tag:T8XugGQF5VX09/Ewa88JTg==,type:str]
    VNC_USER: ENC[AES256_GCM,data:Z0nIWwM=,iv:omozUQNZFtMhk0eks2YqvT/bOB1aJxQnWhDgwbVsUDQ=,tag:MIXjmQif/Tl1+m2wOIRVBQ==,type:str]
    VNC_PASSWORD: ENC[AES256_GCM,data:Z76jeddeWcA=,iv:IVcquxSS78Dn/AH5wPmUpj0d75Ic17mu4MLLAe8QnLc=,tag:l1nervVOG7UxJj8oUQ2jnw==,type:str]
    SECRET_BOOKSTACK_DATABASE_PASSWORD: ENC[AES256_GCM,data:xAmauXkfC4E=,iv:mR0oA4hzFVLou2v66C+GvAbSTCE0XtS2ZcI+5MmeYGI=,tag:rGLs70OX2R0F0R12+4eA3g==,type:str]
    SECRET_RANCHER_ADMIN_PASSWORD: ENC[AES256_GCM,data:TMgWEAv7eHo=,iv:7NDWFgIJQOgAgfiW5Fr8wsenE+SBoLgXQwDQX7v98Kk=,tag:VSpnOseZcyg+McTTdhvGtQ==,type:str]
    INFLUXDB_ADMIN_USER: ENC[AES256_GCM,data:6vtwsYE=,iv:An7i2HbBFpUHaICVSijCHR6MAP4UfNrOOgoZFsBHvF4=,tag:qAespuyySKx006k118kOug==,type:str]
    INFLUXDB_ADMIN_USER_PASSWORD: ENC[AES256_GCM,data:HVCFMZQeQ78=,iv:kmanhF7V6NTri2K1nd59y5rHqDV1GKlWpGHTR98gQqg=,tag:1z03osNzvjihh6X92QMLPQ==,type:str]
    INFLUXDB_ADMIN_USER_TOKEN: ENC[AES256_GCM,data:IYdePT60oIAAgA==,iv:scoHgTKNv6d2rTcmMvpUDe24DlE+69kxnERNpvGnrjk=,tag:lgKPhwD/17D9ePcT/WI4fg==,type:str]
    PGADMIN_EMAIL: ENC[AES256_GCM,data:Y9wRn4vC8zbiBnkq4KnjdQ==,iv:UfJpV5/rA9WXe9bUC3uau440CTdzr2eSZ+Um6PVsauw=,tag:wMBCxzGv7NG62nONT21Krw==,type:str]
    PGADMIN_PASSWORD: ENC[AES256_GCM,data:bBs+W+mOtNk=,iv:EsPr3mqHp9SqtD82ECicl2eeKgY7SOYquOrr/CYBQ7c=,tag:uuzwKQ/LCSAnwHrShxT0uQ==,type:str]
    AUTHELIA_SMTP_PASS: ENC[AES256_GCM,data:U/a1/hVuDxoR1mcjpctTQA==,iv:+C9nFdOMDQlDGXR76oQsUu3vhBCTSRT5nN37X8ztbW8=,tag:rTKjc+6dIbg5GPRkagNp4A==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:Z+v6WXo+n8A9DGw=,iv:zPKhLHlYgrNaoKPV7PhTtPhrO75Sdd/tcEcC3uwYa2o=,tag:A0bS35qNTOADv0C5g04d7g==,type:str]
    SECRET_OUTLINE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:+Pa7NRjkHIbka4HdpmJ29vwu3tdV5ZqcE1I=,iv:mOKW5DUNmepO418MdChuQrcgjxEsgxe97iyXcNmHIoo=,tag:/cbotbFn7T4gj5MWKQk0pw==,type:str]
    OUTLINE_POSTGRES_PASS: ENC[AES256_GCM,data:UY+aqZV2lb3PAbTtcYjwn9DCXg7pa2OYFro=,iv:dUMfv3fdr/G3rYeLtmzx12JLxh3wULiTU1aXISC+GCs=,tag:vlEr3wYiQx6JNNWfRamTfA==,type:str]
    OUTLINE_POSTGRES_USER: ENC[AES256_GCM,data:qemHPClFtQ==,iv:9z5JwGN9IcfL+uvqOkRqF5ORo6iT9mamspxOd5qGh3Y=,tag:QxZApWyJy+YejmYNgpJplA==,type:str]
    SECRET_GITEA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:lKnOr/jlSbiRrbRG7C2YDvg5fYhO72cREls=,iv:vCtayVkSdqIGs9lQdC1558XKLo7yli57vGVL8e/TYsE=,tag:016tfpfLIi9QUnWCRxfI7w==,type:str]
    SABNZBD_API: ENC[AES256_GCM,data:c9/+X7DDy0oLRzvQNifee5b9mbF0vx4unHL80W+zhxI=,iv:diGC+Fm58Eybq/na7oy4foFe0l69UzUP3hhdNqNzbUw=,tag:h+pkRCALjsDwXaQQHOjqXw==,type:str]
    SYNO_ADMIN: ENC[AES256_GCM,data:o24F9T4Wrsk=,iv:8vIYoyqG0GSs/SUiNDTqhTWPrl5QqhZZHZnGbnxJ2R8=,tag:dYmAx1YsjX9RigniMztcug==,type:str]
    SYNO_PASSWORD: ENC[AES256_GCM,data:RAu0IYBsjUU=,iv:7q5gXAVUGH5vVev7MuHzQctbWHT8JgfNre8jTYcVj50=,tag:poi3crRHt4bftPb69aaJbw==,type:str]
    NAS_SERVER: ENC[AES256_GCM,data:BLSle7nKwcfk3Ik=,iv:zE7a3JzqPw99UCEqfHmM7KlKkotiMLIFpJps0OwBwlk=,tag:1beaGNGdIT8O6e/LntJOFQ==,type:str]
    QNAP: ENC[AES256_GCM,data:jUwCqyGYc4cUtiY=,iv:9d8ICTzhAGJ6kuBC0lRy7HoprBibGxn1o2yBiOnmXzA=,tag:VurZ9J/l5/tsD8WoM3AWAA==,type:str]
    CUSTOM_WEB_PORT: ENC[AES256_GCM,data:+IeIhg==,iv:uXyBdaCg56AZiIikYDEBdRbnAtxmJdctSmE9yg4aUBs=,tag:xJqiD20zf57RsWOdVWhGYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13zy8tnl795dry8956zwaa9czept9erhcz6cvrup8md4p0s9465jq83mnp9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzY1F4QTV3NGNQZXdQV1Fn
            OEtpVkhLeUpYdHVsenovMjI2enlWT0wzWm5vClA1OEZHSnRPUFFGblQzTkRXZzBq
            eG0xVDgzZWZTc3N2M283a0tXK1RvWnMKLS0tIEdwOUowVzZuQ2pSTnRoYitEQ0VK
            WkRveEN4c1dqdndIVFQ5Vk13ZGdEWkkKoVrgos1k9RTQ4axb9K2I9VBOuctSclx3
            kHN4v7tAy6DdXnBPfgoOUpmoOZRiRVgcFwIFV+JihkJH4Y6D13yqDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-17T00:27:31Z"
    mac: ENC[AES256_GCM,data:0Qyt3QXGV16y774c3D+jTMsvomK0fEsdpIjFVuNM2SQOxrUjrwoyW1jHny9fQGnPbBqXcbbS1xTdhT/ZMZ9TmcpfbpCl1GHNhME01FEXOulUI2oOOhU4nE1I13h6ylnnoMDEORiJPKkdpHq79jV/nW/fXMCXfGLz17chTaXX5J8=,iv:dDsNLEGdknS81mDp2esG0xPojWj2b9+anVb8QwVv+vk=,tag:LhevDbHyJFfoCxQZdRkSwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
