apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:cGChi2mtfSr8vcs=,iv:dsYVgHfkbD/hI8azOmhaucpwkjXBDxTp49ZSsh41Lig=,tag:FpxsmqFSE7KLwQccbjLF8Q==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:uJB9uMmOB343zu2lSItGtQ==,iv:k5PkpDRQoITTi9+aFD9DrLvMQAoMrCqFB6YOHoYhbKI=,tag:U7pe3w0HLMctf+o2f5TjtA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:DJiefKTLhx7RoFNbIq+AKSqpYwLAIMiOXryYczr+AaF7SGV/,iv:y0cy3txBwP9Mb1d0A1l0in6BwrRj/QNeD/kpk+zBMAY=,tag:NzJEsGW7REIJVJBysU5JJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13zy8tnl795dry8956zwaa9czept9erhcz6cvrup8md4p0s9465jq83mnp9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cDVqS2h6ZDh2SWtoUWVX
            MHJJazdualY2LzN3R0ZFYkY0TkowUHhTYlVzCmNrRjQzUUFWak9GN0RTaStCbTJE
            dXZ4ZXhGZUVQVXlHSVc3c2o2dGhyZ2MKLS0tIHRmYTREQ3Y3L3NHRzdCTk8vMGZL
            c1V3ZHFDVk5pNGdiUzlMVWZ0dEc3OEkKIW66c0xNJoN5m8wOQbM9C1WwM8Hu+nKr
            STZrknnLlveCB4vHGy6ObgNhRYzW157x6afPebosMj6MkMbSuV+Q7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-16T21:00:53Z"
    mac: ENC[AES256_GCM,data:huaWB0BrW8bNTiNlHLWQ9aObrC+DRXHkpzNcwPVa432FSMRBwnYYlKwe7P5Hrw74WML0tf3dFEDpKbR/XROHkjfoDc7/RwIxSO6wwbVL+5dLavpOAD7AWR0GlISg8nfbz98k8+FeqXD+SrgYznlPZPGAHJsBYI0xf/bIJMsQcNA=,iv:hR3mPvF3YJYGzTs2Vsc1Bksw393H/+8kNOgX9571IYY=,tag:ODtVgwbgAnzGd6IDKVmfUw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
