apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Zddxb95vnyh1d5M=,iv:k1+jF/3odup/bXDQHVHW1yaXLJYAJqk2nl9zVlmHUqk=,tag:3CJxp5keuKD6ubdhP3+M5Q==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:/tzuY0+z1S8nlAMJTU+m5g==,iv:JnV7VHqVlmaO+/ETIhmfkrd63ysF0EcTyfM4+usX6uo=,tag:kycri36D4fWY8qAjWgkJ+Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:b0QlSOM9JWxvhDZERBpMcWUj94f5DS4aiek1lKHKtEf04idP,iv:Pm3U8a7u27FtEfM8Z0vJoIvtsDIxGqHHgY44TKgNgaI=,tag:H8oe4VjpDkkfDHR8Zg860g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age173zs4ye5tp5ulaujj9p4ngg9azsmm8z3a0ayma98ugxudkrr5qqq6n52qt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVWFRSkpXVTV3Mjd4NnBT
            WFhzNHlIQ2hqbW9rVjJnTUVoR2FxUzhFZlRnCk1RcXloaDBTRVIyZkhRSE1jQjlU
            MHhka0Q5NjhESHRvM0d1V3EwSHJkc2cKLS0tIDRnQU5kVnRnMjZhOThKeHRkVkQw
            RS9WRDZNdmNTMHJkTnk1MlZtTEtoa00Kf35zE4pbwGELqf5ISxKeuJV5aU6MMkP8
            Pl02YeA4QkSKw3Ap7vI25vUw11MBP3AgukVb6EwHwTdZk+JJ6sT69A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-27T23:37:08Z"
    mac: ENC[AES256_GCM,data:nx7UobZg1VQnXWk+YE3uBAR+rsW4Tm5oKOT22p3o9a9P7unwmLVl3OHynSoNO2L3/IshttAldw3ynDq9ZvUNfHKWhJQhLoUxiA7DlVncMcl3t+kLzv8/TJP43TNgvNT82xgXMmT6/jQEOO1RtFKLmkmLOMlqbUi0gfZrelB9ZaM=,iv:39aOcVJpDbW7DIjtnpHu128SXetf7I2fEaustGVIEnQ=,tag:yCrKhqHGlY26JlTZ+YtTag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
