---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: speedtest-exporter
  namespace: downloaders
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
    controllers:
      speedtest-exporter:
        containers:
          app:
            image:
              repository: ghcr.io/miguelndecarvalho/speedtest-exporter
              tag: v3.5.4
            env:
              TZ: ${TIMEZONE}
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                cpu: 100m
                memory: 100Mi
    service:
      app:
        controller: speedtest-exporter
        ipFamilyPolicy: PreferDualStack
        ports:
          metrics:
            port: 9798
