---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: loki
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/apps/observability/loki/app
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: onepassword-connect
    - name: rook-ceph-cluster
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: loki
      namespace: monitoring
  prune: true
  wait: true
  interval: 30m
  retryInterval: 6m
  timeout: 5m
