---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tdarr-node
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      securityContext:
        fsGroupChangePolicy: "OnRootMismatch"
        capabilities:
          add:
            - CHOWN
    controllers:
      main:
        type: deployment
        replicas: 3
        containers:
          main:
            image:
              repository: ghcr.io/haveagitgat/tdarr_node_acc
              tag: 2.23.01
              pullPolicy: IfNotPresent
            env:
              TZ: "${TZ}"
              serverIP: tdarr.media.svc.cluster.local
              serverPort: 8266
              ffmpegPath: "/usr/local/bin/ffmpeg"
              nodeName:
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
            resources:
              requests:
                cpu: 10m
                memory: 250Mi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: nodetype
                  operator: In
                  values:
                    - worker
    service:
      main:
        enabled: false
        ports:
          enabled: false
          http:
            port: 8265

    persistence:
      media:
        enabled: true
        type: nfs
        server: "${NFS_SERVER}"
        path: /volume1/Media
        readOnly: false
      cache:
        enabled: true
        type: nfs
        server: "${NFS_SERVER}"
        path: ${NFS_MEDIA}/cache
        mountPath: /cache
