apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:ylNvIZvXm2rvSXMRm4XLTHd6SjksQuQqa6AQeJ57Mnc=,iv:cp62rep+AIoiNyxbUQkVnHA96noG4e3hLxyPwlPSoF0=,tag:WQ5CSYdniq6mSNXUyeJzOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13zy8tnl795dry8956zwaa9czept9erhcz6cvrup8md4p0s9465jq83mnp9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzR0l3c0M0VVArNDVJb2Iw
            Yko1eEsyQUNQeEZ0WjhRaDN1ZEdHU1hDd1M4Cnp0MVhqKzZRR0Vkb0ExSXhaY3NJ
            YkpQa1hhbkdOSXJsOEx1OUlLWkVRSWcKLS0tIGQzclR4T2NmYnVOTTljTWM2YXY1
            eDJEMnJlYTFKaStZbVh4SXJUSUdkRlUK4SQVHjbpsI2wEMqSUlkIzKdyAWemVEH2
            uBtzGtkyfgUzQCNAAWBVvZJDqQotxysBlE+QWpa1ei+Bxwx34PFfYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-28T05:28:20Z"
    mac: ENC[AES256_GCM,data:noQtbrEoXYRLok5w8m1Pys3mXVa5D7EgwBD6Gih8tJrndUhfvltxzDoWghnZvAT5/Yn8B+nzwXeVJSnAQNW1Ic8cQgO7QAcDnkgMOgALaZfK+p3BWo0hQDIhIG9nwMFO6EKDPG3vhLay4geXu+ourW6z7Sm5MYr0vbXfa3vBQpY=,iv:zQFTHKL3nf37NDINlEKqghl60/hO5zqntvQduuTkMj4=,tag:+GvNuu5gOXOaB4uOsMEPLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
