apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:tlRmdxP15UJTZlK4TUlZMJtlWAXzHN2e7KV0p5QsZHQ=,iv:qZOiEd+EBeK4p3wQsADeKJtSilp1xpl0OXdNVet1dc8=,tag:skh2LnAW6q4JN2WYWSpPDw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13zy8tnl795dry8956zwaa9czept9erhcz6cvrup8md4p0s9465jq83mnp9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPd3d1OUFIMXNDOURZc3Zz
            cFBvanB5UmhDVml3Y2IyRklVRzBDa3hoMDBVClRFQUMwWTM0VkZSVjVjaXc5T0V3
            ZnRKOUFXY1hmL0hTRFBUSmpXUHN6UXcKLS0tIHBQR0J0dEtwWk9HUmg3UFBQRmda
            NVhpN3V4a0pabDJrR1Y1cDQyU3BndFEK9urxGpjv6/Q7C1+9anazYn5EWqzttPyf
            boM2nd+Cklg0UMzErybVtwLxpigBSPg/cjbO1+1gR/L/gO5mJC6DxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-16T19:29:41Z"
    mac: ENC[AES256_GCM,data:Y9ozB+/pH5BYEIs0VMIPXQCkEnOX7g7pXk9yjGtdpFgeN/02ELe33WLSi+z2iL9eiAk/VdwDb3fuUyzvmznaJLyRqSG/BepvqG/EO6DVgskHSyoGSvqoPmkTc+mJqG/YjWa50ryqcEuKEGERiHgq32+fXnNnK6O1GiLigA4v9/s=,iv:5aNxxhwOCPzROYk4kx6mdoJL1m8BK7D8efIzs+IsqTk=,tag:q4VGO6DJOhpggM+tR978Ow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
