apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:qwEC6XAWZEruh4TQ6W0KhRLgAiI03TwK4ywCwzTpy4s=,iv:bROdb8RlOXBJIoFdwgo/sNlJ277VRZTm43UgFBL7/1A=,tag:nUBdOOtMuKZeZAPsshvgFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17mejdfq9mpp3uhqenmtrhuxs598atx33telpakcwcp59wzrg3q6qcl34w0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdlVGdmU2MHp4MTZzR1Rw
            ZFdpZ2xIU3U5ZmJDaDNOSlZ2eTcxZFpMTnpzClBGaDhCdy9wYXRhRGZBaml6bVYx
            ZkhtN0VETjFtaDl6M3kyRzVZeU1xaWcKLS0tIG5jeDB0UGkzWStxcFU5Um9oTllG
            OEdvWmFzR0picEkxQ082aEs1QnNwUGcKNOPuqvn48z6dkoXz0xSi11pDraruf9T9
            lLOt74I2dVsTM/pdkV4kQ8ztez992us/UK76LYvJXbU7D8aXMLlbCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-27T02:54:57Z"
    mac: ENC[AES256_GCM,data:mSNPZyyB9ofEsJrgHRQurSqg9clYsH6+3fePWEBNv9jB+Y5/wM3vUosRC5hWiOBprjhPGuYscZLzHXyhwuEMi68A19vBl6Rxpb7TbTa5gA5bEUwFSRGOB7fvw/Vc1l1fGr4QN2gn0HuzXljYeBFjh1GU5JW0E7iE3TjbkSjkmfc=,iv:gZOxNsQ8XQIOFbZVdPrjwsmbPLcHnD39eNwRzReLNZo=,tag:C6JQMZZXLVupuBbiYzFnkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
