apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:cZdPstQQF5PwaQM6303nvvhKpqmw8L9sjmOIOvsiv9c=,iv:D+P06vjzWlggJKRH3YmiYurioHBbKarb15P6VF7xeK8=,tag:g178bH2t711TpR6t6sXzDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1grgjnv8zu03gjh3t2m6dr0pk5e97wg97d2szgn0laeyjgllz0g6sq6e4s3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTXNxNUJUeGd3UkJlUUxk
            aUNKaVBzQ0EzVlZrb3pSenJsVXdEVU01NjI0CnR5TGo5YTAveGdocjduTzMzRy8y
            UlZaeXpzdU1mNm5wUTBra3MrajZiTXMKLS0tIEE4RUpPT3VlMmZtUkkxZDE1MXpS
            SmdPYlh0SHdDcStJdDN6d3FBVnpESG8Kw03cxREX7Vpj2h1e3Uadm3RCHiIdT8Uq
            024+gMlRN6CUs8rUdxFb3i7hzPxWsDIeFIg2cXId7LZDBQLLHMbqGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-28T03:58:29Z"
    mac: ENC[AES256_GCM,data:vIy+xe1VDiZuuBq/jwlGzY+D151PYRd0WhDzOVNCgcspbvc1A/ZoS1QG1WejOPJiQmoo2by/eWPzsUdS6ht+qZFQ+lvaM64NktWXlDlvKPK6fyT4FjTw1wVpxGMsYyxt+KVKMprfQ2WZf+8vPUtNJBz4mfF7VeLkbMOiVDyTvKI=,iv:Th+yBGiG9+iDJKpmAzyUrcp1gvqyFWsCkRhZ5wM3EMI=,tag:78oTaO7yx91GcFuLj3yRLg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
