apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:JQYDJ9qqN+DN9KB+Dmfav5NjoG7K7tisS9JMWB3n56Q=,iv:VOf9X84dnGITQqddEiEnD6ZJ53L+yqA6fbNRR2bHyNU=,tag:i4u8KZjOFC8n1FAzDtIfLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13zy8tnl795dry8956zwaa9czept9erhcz6cvrup8md4p0s9465jq83mnp9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWaFZWNUlHL3N4UHpXVEtD
            d1lsVnp2Y3ZQU2Z6MGNCUU5sT2lINEdCS0hjCkdUam9ILzY3VHV1UU43OWlKNjZx
            M0pvMWNNQUVsNDU2NWt2dkNTbXFLZU0KLS0tIGRwMzRUM1VLNnFRU3VVRkROU08w
            UDJ4T2lQcWxCcGFQV3ZZSE96OW9Ra00KnG8Q3ynbPMjszVryu2kK5wFXgobt2+59
            nadZYellEvtyR707B2++sdUFhigGCkfgyfAdPOdyXagvI48Ng7KEOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-16T18:50:41Z"
    mac: ENC[AES256_GCM,data:IBQozdwVCJ+3FKf8rjJe7/g6sZvbJZYh+YsHVRQTW91jMc2lRCt942rgEiphrLX0XFMvK07S7xF6M+L2xt19eGZZIhqVNo+KFald+7UZYijCZquPRxhYC2RrE7Tp2vFxEUHpBABNdpIpMs8yK0Z5AKwow3gD6u1dqx0A7M93LR4=,iv:XOq9gD3PZCpViUmP83IYgyHwpL5w9LUQ5MLHYwRzjhE=,tag:rZq7TjGpeCGWc1UEnMvqWg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
