---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jellyfin
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: "./kubernetes/apps/media/jellyfin/app"
  dependsOn:
    - name: rook-ceph-cluster
    - name: onepassword-connect
    - name: volsync
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
