---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: homepage-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        HOMEPAGE_VAR_SONARR_KEY: "{{ .SONARR__API_KEY }}"
        HOMEPAGE_VAR_LIDARR_KEY: "{{ .LIDARR__API_KEY }}"
        HOMEPAGE_VAR_READARR_KEY: "{{ .READARR__API_KEY }}"
        HOMEPAGE_VAR_READARR_AUDIO_KEY: "{{ .READARR__API_KEY }}"
        HOMEPAGE_VAR_RADARR_KEY: "{{ .RADARR__API_KEY }}"
        HOMEPAGE_VAR_PROWLARR_KEY: "{{ .PROWLARR__API_KEY }}"
        HOMEPAGE_VAR_ADGUARD_USERNAME: "{{ .adguard1_username }}"
        HOMEPAGE_VAR_ADGUARD_USERNAME: "{{ .adguard1_password }}"
  dataFrom:
    - extract:
        key: sonarr
    - extract:
        key: lidarr
    - extract:
        key: readarr
    - extract:
        key: radarr
    - extract:
        key: prowlarr



