---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: homepage-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        HOMEPAGE_VAR_GRAFANA_USERNAME: "{{ .GRAFANA_ADMIN_USERNAME }}"
        HOMEPAGE_VAR_GRAFANA_PASSWORD: "{{ .GRAFANA_ADMIN_PASSWORD }}"

        ## Cluster resources
        HOMEPAGE_VAR_SECRET_DOMAIN_NAME: "${SECRET_DOMAIN}"

        ## Media
        HOMEPAGE_VAR_LIDARR_TOKEN: "{{ .LIDARR__API_KEY }}"
        HOMEPAGE_VAR_RADARR_TOKEN: "{{ .RADARR__API_KEY }}"
        HOMEPAGE_VAR_READARR_TOKEN: "{{ .READARR__API_KEY }}"
        HOMEPAGE_VAR_SABNZBD_TOKEN: "{{ .SABNZBD__API_KEY }}"
        HOMEPAGE_VAR_SONARR_TOKEN: "{{ .SONARR__API_KEY }}"

   dataFrom:
     - extract:
         key: adguard
       rewrite:
         - regexp:
             source: "(.*)"
             target: "adguard_$1"
     - extract:
         key: cloudflare
       rewrite:
         - regexp:
             source: "(.*)"
             target: "cloudflare_$1"
#    - extract:
#         key: email-service
#       rewrite:
#         - regexp:
#             source: "(.*)"
#             target: "email_$1"
    - extract:
        key: grafana
      rewrite:
        - regexp:
            source: "(.*)"
            target: "grafana_$1"
#    - extract:
#        key: home-assistant
#      rewrite:
#        - regexp:
#            source: "(.*)"
#            target: "home_assistant_$1"
    - extract:
        key: lidarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "lidarr_$1"
#    - extract:
#        key: navidrome
#      rewrite:
#        - regexp:
#            source: "(.*)"
#            target: "navidrome_$1"
#    - extract:
#        key: overseerr
#      rewrite:
#        - regexp:
#            source: "(.*)"
#            target: "overseerr_$1"
#    - extract:
#        key: plex
#      rewrite:
#        - regexp:
#            source: "(.*)"
#            target: "plex_$1"
    - extract:
        key: prowlarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "prowlarr_$1"
    - extract:
        key: radarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "radarr_$1"
    - extract:
        key: readarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "readarr_$1"
    - extract:
        key: sabnzbd
      rewrite:
        - regexp:
            source: "(.*)"
            target: "sabnzbd_$1"
    - extract:
        key: sonarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "sonarr_$1"
#    - extract:
#        key: unifi-poller
#      rewrite:
#        - regexp:
#            source: "(.*)"
#            target: "unifi_$1"
