---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: readarr-audio
  namespace: organizers
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: readarr-audio-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        READARR__API_KEY: "{{ .READARR__API_KEY }}"
  dataFrom:
    - extract:
        key: readarr-audio
