---
apiVersion: v1
kind: ConfigMap
metadata:
  name: readarr-audio-gatus-ep
  namespace: organizers
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: Readarr-audio
        group: Organizers
        url: https://audio.bharris.vip
        interval: 1m
        client:
          dns-resolver: tcp://10.0.111.20:53
        conditions:
          - "[STATUS] == 200"
