---
# yaml-language-server: $schema=https://raw.githubusercontent.com/JJGadgets/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  interval: 30m
  values:
    image:
      repository: ghcr.io/bjw-s/calibre-web
      tag: 0.6.21@sha256:9049b3a3e9afa19f189dfac69db0df944d4638247acfed1f69606e4dd8b7e841
      pullPolicy: IfNotPresent
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65539

    enableServiceLinks: false

    env:
      CACHE_DIR: /cache

    service:
      main:
        ports:
          http:
            port: 8083

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &host calibre-web.${SECRET_DOMAIN}
            paths:
              - path: /
        tls:
          - hosts:
              - *host
            secretName: "calibre-web-tls"
      kobo:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &host_kobo calibre-kobo.${SECRET_DOMAIN}
            paths:
              - path: /kobo/
        tls:
          - hosts:
              - *host_kobo
            secretName: "calibre-kobo-tls"
    persistence:
      config:
        enabled: true
        existingClaim: calibre-web-config
      media:
        enabled: true
        mountPath: /data/nas-media
        path: ${NFS_BOOKS}
        server: ${NFS_SERVER}
        type: nfs
      cache:
        enabled: true
        type: emptyDir
        mountPath: /cache

    resources:
      requests:
        cpu: 15m
        memory: 249M
      limits:
        memory: 299M
