apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:Greq5eceo5OgqgakQn2eKJt6haXoaF7oHv5emwFgf3zOrugUj3Qr6g==,iv:poiuDgVvTeEffKRNXFFIhIClEWwZFaoUNPP+VeZycyc=,tag:t2zwfK3lt5OEojw2RaskqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age173zs4ye5tp5ulaujj9p4ngg9azsmm8z3a0ayma98ugxudkrr5qqq6n52qt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RnQzc1hIYmRHQUkveHFj
            aXlaUnNET2hTeUt5aiszVjNHcFlSa0JaZmxNCnNhY3o2Y2VyT3lsejhvYXZrSEl4
            cUN0U0pwMTJCVnFhZThmZDFzYWlRTEUKLS0tIGlTTHJaZzRIbDI3SWR2aW9mYW92
            OGNveXNMak9MNWhObFQ1bkdpd0NLSlkKEl73aH4ieljPhBscXYlcGcwM1LH/4dOD
            McAavQvmTJyHizqdrzJzfwja+6UttVID1lPj0PVGwwFSCWDmD7EcZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-27T23:37:08Z"
    mac: ENC[AES256_GCM,data:/x9BQyvlj9yHl6Dm3Ne5j4isuz7Drxt/VfDVZ33PByhG2DGebloM1pWx/DF9kMdffJDz+Js8Tr3vXR8HhBfpebYUTT4l7qgkhtBLEvasTTuRJB7jNtRgKat9ZWUe9xHNnXoE2TrLdSSrQ4cCQp4jfiYNbwZVVPUQWmWlktU1ZmY=,iv:5SNLrXAebws8qijs1Q8AkWc0Ag5CNFeCxisgYYjJ9ng=,tag:Dw4wruRvxXO7WfZ79recXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
