apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:gT6MASPzIbEle6pcMP895doBGMUPNFxopd7i8WTA7qN4CS7Cuco+Lg==,iv:tpXNxgoPBXog9/5ncg/3zam3GRtc5nU2m3saqgUbZ/c=,tag:7DRlm5szUmZoJzmQkGev/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17mejdfq9mpp3uhqenmtrhuxs598atx33telpakcwcp59wzrg3q6qcl34w0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SmpSTGh6SWtYaGNKWHJQ
            SjVJU0krRmI1VE9SSDJhT2tZbmFnTUF6U1FVCklJZ1JpbUVBTnFDWnJsQ3ZoSzRp
            dG1vMC9INzQwS2RrMHNSSy9IbFVQZUUKLS0tIG5vQ1NDK0JSQjkxNUQ4WFZ6SW9P
            QUdQbW1KV1pCSitsMFVVRXY0MDdtRjAKuvn4BtqhfT4rs/GJ8VGZexpp6s1wN1Dz
            3PDxwNT8uuZA7qtzo8qPiUxJn26wBIl1+dreUCZItIW3RxnZDHlHKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-27T04:17:37Z"
    mac: ENC[AES256_GCM,data:EAgDT1QhHhDN8HgTwsViRBcCOz8j+0ndxLSCA4GBD9h8sqstRyOXtGqYYtNI5t9bQjTwm01h2Ipyu6vZTCMXXKlRRzBNFJLSt+X/qt1DMuRcAYXXJyQn7xQ8jyFUfd/V3w8OA+Y1f3pLuQciAeigHTOtyp2LEv1obCAANhutpZ0=,iv:lTl/KyGCbjbrBOPCgGdzE4kTp1TmtcCcQWKY5n/T6zY=,tag:MCvaWLDYElZWIoedktUFow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
