apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:DNYdcaE7foIaSXjyj8Ewh74YwnzxjfA8cdP5Zbyd4D7QcFmKjVi5jw==,iv:9Sg2n20Udwsz6HltFxUeQUbAzXJL1w/D+zxmjTgOXJU=,tag:5jp7zM6Pg6YHlTzIzTxGVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13zy8tnl795dry8956zwaa9czept9erhcz6cvrup8md4p0s9465jq83mnp9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaY2d5SGQzSEZVMGJJWVA2
            QUk4d1F4b2xpdjl1b2lHM1Z6eWRNZCtGUEFRCkVuemFMNnI4Ky9hY2VHSWQ4b2d2
            TGtWWnBHWXc5dkpRRDZkdVF6MTA2bE0KLS0tIERYK0FvMUtqVlpXNVZtWHZtVmJQ
            dGwvaStUdGUzUkxSODRPQkZ1SEt5UkkKst6ZkWNFGVezvGB2oyn7TCmivJb+0kCI
            bNyxzZpaTIe2rYnp/khWRQHV6qXyoDDJrqd+VZQPjpyGTSxW8TeU3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-16T18:50:41Z"
    mac: ENC[AES256_GCM,data:jSBOfybOlwnknpwjtSb3aYJJgGEE7F58McjAMxyPzB8pm6Fsgi1EjlmSkjHkjxhNrc33lUPmyIHt6wnF+0TfnsLlmeOJ47uzeGXsttVXrcg/qRmvtWG754zytsXKcSbu/gyqm/BzOAm9MbUvyqvMMMqFtKG3sVcXxN9bTIRvi0A=,iv:EJC9e+bxLNDzzEZYO3GplHM6PAtukTxzbxH8IYkTSRE=,tag:uMFc5p+1yDCm+HW7dR+Zzg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
