apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:ILnKdrjHEV/MHsAfr3X2mG7uWuBL8qSXupIGkmbI2UgOL9S8BMFVYw==,iv:pPyzLqBMbRXGzyf3i4ioan+6lx5XuZWBexNQB/NOImg=,tag:wRTQM55vdhAejAnC+6Av4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13zy8tnl795dry8956zwaa9czept9erhcz6cvrup8md4p0s9465jq83mnp9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMVZIaWVYdmxVdDVnUnpt
            eWNmWFQxMUpJakpSNEF0S2ZqektuMnVJSFZvClBCK01KQ0orTGZ2U2JwZ2VPbVNN
            bkNsQURrbC9DTDNkNnJRNU9Bb3dTTlEKLS0tIDB6L1dpRllxUTZ4MW5IRkxURDQx
            T0poMUd3Q0tBbzZBYjBqWHNGa0VjdDgK1Xpt3j+Se4lIzKyzMzOBfAOHd+l/4JqX
            KP59LH9U9OSZLhnEHsRHNRmMUepoHzCFoPY2Pg+98yc7q7a84DWSgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-16T19:29:41Z"
    mac: ENC[AES256_GCM,data:eQosLeVmWCdey7Rg6aJKLrv60GCeRZ801lqda1PaKVLt699xApI0cJ3zNLKaJ3Ex2Eyj5fvQwscA2VIfUE+Mhsp6ah5troImZ9IxMcKMs2D/5QkfNZgQZlynPW8rCNVHW87bvWlL0fJZf4ot7QKvh7LwTb/5dnKYog1qaizCUlE=,iv:EvQ9WYgVVfqjosVYgzNFoB6IvlMyxLxSbahwibYP8m0=,tag:E3yyjlnIfu1LMWKQ+waNLg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
