apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:eFsX99oNjzzXn5nFLJ3ARWy97v0AIilLjnxDmnPkIziz5TM75fAQ/w==,iv:Y2IEWBB7GKI5/ZDUP3ypJSo2JMv9XPUQyerLj29a96I=,tag:MlsVgiU9XP9fwyhpAKk9CA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17mejdfq9mpp3uhqenmtrhuxs598atx33telpakcwcp59wzrg3q6qcl34w0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbDVKT1dLZXZhMHVzRWNj
            Ri8wQ285djBMOEh0ZzdQT2htWmhyTldBa2o4CngxTXR6dXVZeWRrUUtMbGEvbFdY
            dkhNbUZ3ZU5UWlAxSzU0K2VTZEl5aFUKLS0tIDhTaHIwNjNMNUF1RE5nUDVpR2V3
            a3RZWi83andCeHhxTlJRUUxhVXRWS1UKk8wKCcWoEgEo/ZX0fgOh3sJfyw0zGNFu
            GcptsPw3YqVFhNBlyY+KkEEtk8ijRfMpzpNRNDTqE/SsneC1sVfntQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-27T03:13:41Z"
    mac: ENC[AES256_GCM,data:URhFBYkdJ1KSOD6Jwo069F2nfod8ZTMDNe446dI22y0iUGPnzreopnJO4yrOyHMQHejs0bBlHT7NfRQZRze319C9Lwm2QI/jq9nWfJGd9vb5FTn6MqcN7qLYiWZ59w/VesNCKK0dYI7boBB1T0PLMI3t21xE31W9npYvuM99vXU=,iv:c8/DRzoUjJZk6HBSrUuOkgXxowp9pY9LbtuCVqlT/Ig=,tag:6Zf1xWnbjX2f1Ilnyb9R2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
