--- #
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authelia
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/apps/security/authelia/app
  prune: true
  dependsOn:
    - name: onepassword-connect
    - name: rook-ceph-cluster
    - name: cloudnative-pg-cluster
    - name: redis
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
